import type { DispatchJob } from '@/types/dispatch'

function today(): string {
  return new Date().toISOString().slice(0, 10)
}

function yesterday(): string {
  return new Date(Date.now() - 86400000).toISOString().slice(0, 10)
}

/**
 * Demo zákazky — každá v inej fáze procesu.
 * Technik vidí na dashboarde celý životný cyklus zákazky.
 */
export const DEMO_JOBS: DispatchJob[] = [
  // ── 0. Marketplace — nová nabídka k přijetí ──
  {
    id: 'demo-mp',
    name: 'Nová nabídka — přijmout zakázku',
    referenceNumber: 'ZR-DEMO-MP1',
    insurance: 'Pojišťovna',
    category: '01. Plumber',
    customerAddress: 'Na Příkopě 33',
    customerCity: 'Praha 1',
    customerName: 'Alena Svobodová',
    customerPhone: '+420777000007',
    urgency: 'urgent',
    createdAt: new Date().toISOString(),
    status: 'dispatching',
    techPhase: undefined,
    crmStep: 1,
    scheduledDate: today(),
    scheduledTime: '15:00 - 17:00',
    country: 'CZ',
    subject: 'Havárie — teče voda z potrubí pod umyvadlem v koupelně. Zákaznice prosí o urgentní příjezd.',
    distance: 4,
    durationMinutes: 10,
    customFields: {},
  },

  // ── 1. Naplánováno — vyrazit na cestu ──
  {
    id: 'demo-1',
    name: 'Oprava odtoku v kuchyni',
    referenceNumber: 'ZR-DEMO-001',
    insurance: 'Pojišťovna',
    category: '01. Plumber',
    customerAddress: 'Vinohradská 42',
    customerCity: 'Praha 2',
    customerName: 'Jan Novák',
    customerPhone: '+420777000001',
    urgency: 'normal',
    createdAt: new Date().toISOString(),
    status: 'naplanovane',
    techPhase: 'offer_accepted',
    crmStep: 2,
    scheduledDate: today(),
    scheduledTime: '09:00 - 11:00',
    country: 'CZ',
    subject: 'Baterie v kuchyni kape, nelze úplně zavřít. Zákazník hlásí problém cca 2 týdny.',
    distance: 12,
    durationMinutes: 25,
    customFields: {
      client_diagnostic: {
        description: 'Baterie v kuchyni kape i v zavřeném stavu. Problém trvá cca 2 týdny, zhoršuje se. Pod dřezem je mokro.',
        photos_count: 2,
      },
      diag_result: {
        scenarios: [
          {
            id: 'plumb_dripping_faucet',
            category: '01',
            title: 'Opotřebovaná kartuše baterie',
            probability: 85,
            cause: 'Keramická kartuše baterie je opotřebovaná, těsnění netěsní a propouští vodu.',
            procedure: [
              'Uzavřít přívod vody pod dřezem',
              'Demontovat páku baterie (imbus 2.5mm)',
              'Vyjmout starou kartuši',
              'Vyčistit sedlo kartuše od vodního kamene',
              'Vložit novou kartuši (35mm nebo 40mm dle typu baterie)',
              'Smontovat zpět, otevřít vodu a zkontrolovat těsnost',
            ],
            requiredParts: [
              { name: 'Kartuše baterie 35mm', brands: ['Grohe', 'Hansgrohe'], materialType: 'plumbing', qty: 1, unit: 'ks', priceCzk: { purchase: 180, sell: 350 } },
              { name: 'O-kroužek těsnění sada', brands: [], materialType: 'plumbing', qty: 1, unit: 'sada', priceCzk: { purchase: 25, sell: 60 } },
            ],
            estimatedHours: { min: 0.5, max: 1 },
          },
          {
            id: 'plumb_corroded_valve',
            category: '01',
            title: 'Korodovaný uzávěr pod dřezem',
            probability: 10,
            cause: 'Uzavírací ventil pod dřezem je zkorodovaný a netěsní v uzavřené poloze.',
            procedure: ['Uzavřít hlavní přívod', 'Vyměnit ventil', 'Zkontrolovat těsnost'],
            requiredParts: [
              { name: 'Rohový ventil 1/2"', brands: [], materialType: 'plumbing', qty: 1, unit: 'ks', priceCzk: { purchase: 85, sell: 180 } },
            ],
            estimatedHours: { min: 0.5, max: 1.5 },
          },
        ],
        partsListUnion: [
          { name: 'Kartuše baterie 35mm', brands: ['Grohe', 'Hansgrohe'], materialType: 'plumbing', qty: 1, unit: 'ks', priceCzk: { purchase: 180, sell: 350 } },
          { name: 'O-kroužek těsnění sada', brands: [], materialType: 'plumbing', qty: 1, unit: 'sada', priceCzk: { purchase: 25, sell: 60 } },
        ],
        estimatedCostRange: { min: 800, max: 1500 },
        confidence: 'high',
        analysisVersion: '2.1',
        generatedAt: new Date().toISOString(),
      },
    },
  },

  // ── 2. Na cestě — příjezd na místo ──
  {
    id: 'demo-2',
    name: 'Výměna zásuvky',
    referenceNumber: 'ZR-DEMO-002',
    insurance: 'Pojišťovna',
    category: '03. Electrician',
    customerAddress: 'Korunní 88',
    customerCity: 'Praha 10',
    customerName: 'Marie Dvořáková',
    customerPhone: '+420777000002',
    urgency: 'normal',
    createdAt: new Date().toISOString(),
    status: 'naplanovane',
    techPhase: 'en_route',
    crmStep: 2,
    scheduledDate: today(),
    scheduledTime: '10:30 - 12:30',
    country: 'CZ',
    subject: 'Zásuvka v obývacím pokoji nefunguje, nereaguje na zapojení spotřebičů.',
    distance: 8,
    durationMinutes: 18,
    customFields: {},
  },

  // ── 3. Na místě — diagnostika ──
  {
    id: 'demo-3',
    name: 'Ucpaný odpad v koupelně',
    referenceNumber: 'ZR-DEMO-003',
    insurance: 'Pojišťovna',
    category: '08. Unblocking',
    customerAddress: 'Mánesova 15',
    customerCity: 'Praha 3',
    customerName: 'Petr Kříž',
    customerPhone: '+420777000003',
    urgency: 'urgent',
    createdAt: new Date().toISOString(),
    status: 'na_mieste',
    techPhase: 'diagnostics',
    crmStep: 3,
    scheduledDate: today(),
    scheduledTime: '08:00 - 10:00',
    country: 'CZ',
    subject: 'Voda v koupelně neodtéká, stojí ve sprše i umyvadle. Podezření na ucpání sifonu.',
    distance: 5,
    durationMinutes: 12,
    customFields: {
      client_diagnostic: {
        description: 'Voda stojí ve sprše i umyvadle. Zkoušeli jsme čistič odpadů, ale nepomohlo. Občas to bublá.',
        photos_count: 3,
      },
      diag_result: {
        scenarios: [
          {
            id: 'drain_clogged_siphon',
            category: '06',
            title: 'Ucpaný sifon',
            probability: 70,
            cause: 'Sifon je ucpaný nečistotami (vlasy, mýdlo). Běžný problém v koupelnách.',
            procedure: [
              'Odmontovat sifon pod umyvadlem / vaničkou',
              'Mechanicky vyčistit sifon',
              'Propláchnout odpadní trubku tlakovou pumpou',
              'Nasadit sifon zpět a zkontrolovat těsnost',
            ],
            requiredParts: [
              { name: 'Těsnění sifonu sada', brands: [], materialType: 'plumbing', qty: 1, unit: 'sada', priceCzk: { purchase: 30, sell: 70 } },
            ],
            estimatedHours: { min: 0.5, max: 1 },
          },
          {
            id: 'drain_blocked_pipe',
            category: '06',
            title: 'Ucpané odpadní potrubí',
            probability: 25,
            cause: 'Ucpávka je hlouběji v odpadním potrubí, mimo dosah sifonu.',
            procedure: ['Propláchnout spirálou', 'Kamerová inspekce při neúspěchu'],
            requiredParts: [],
            estimatedHours: { min: 1, max: 2 },
          },
        ],
        partsListUnion: [
          { name: 'Těsnění sifonu sada', brands: [], materialType: 'plumbing', qty: 1, unit: 'sada', priceCzk: { purchase: 30, sell: 70 } },
        ],
        estimatedCostRange: { min: 600, max: 1800 },
        confidence: 'medium',
        analysisVersion: '2.1',
        generatedAt: new Date().toISOString(),
      },
    },
  },

  // ── 4. Schválená cena — zahájit opravu ──
  {
    id: 'demo-4',
    name: 'Oprava kotle Vaillant',
    referenceNumber: 'ZR-DEMO-004',
    insurance: 'Pojišťovna',
    category: '04. Gas boiler',
    customerAddress: 'Slezská 120',
    customerCity: 'Praha 3',
    customerName: 'Eva Malá',
    customerPhone: '+420777000004',
    urgency: 'normal',
    createdAt: new Date().toISOString(),
    status: 'schvalovanie_ceny',
    techPhase: 'estimate_approved',
    crmStep: 4,
    scheduledDate: today(),
    scheduledTime: '13:00 - 15:00',
    country: 'CZ',
    subject: 'Kotel Vaillant nezapaluje, displej ukazuje chybový kód F28. Zákaznice bez teplé vody.',
    distance: 6,
    durationMinutes: 14,
    customFields: {
      client_diagnostic: {
        description: 'Kotel Vaillant se nezapne. Na displeji svítí F28. Už to dělal 2x minulý týden, ale pak to samo přestalo.',
        photos_count: 1,
      },
      diag_result: {
        scenarios: [
          {
            id: 'gas_f28_ignition',
            category: '04',
            title: 'Vadná zapalovací elektroda',
            probability: 75,
            cause: 'Zapalovací elektroda je opotřebovaná nebo znečištěná, kotel nezapaluje plyn (chyba F28).',
            procedure: [
              'Odpojit kotel od elektrické sítě',
              'Otevřít přední kryt kotle',
              'Zkontrolovat zapalovací elektrodu — vizuálně i multimetrem',
              'Vyměnit elektrodu za novou originální',
              'Uzavřít kryt, zapnout kotel a provést zkušební zážeh',
              'Zkontrolovat těsnost plynových spojů detektorem',
            ],
            requiredParts: [
              { name: 'Zapalovací elektroda Vaillant', brands: ['Vaillant'], materialType: 'heating', qty: 1, unit: 'ks', priceCzk: { purchase: 650, sell: 1200 } },
            ],
            estimatedHours: { min: 1, max: 1.5 },
          },
        ],
        partsListUnion: [
          { name: 'Zapalovací elektroda Vaillant', brands: ['Vaillant'], materialType: 'heating', qty: 1, unit: 'ks', priceCzk: { purchase: 650, sell: 1200 } },
        ],
        estimatedCostRange: { min: 1500, max: 2800 },
        confidence: 'high',
        analysisVersion: '2.1',
        generatedAt: new Date().toISOString(),
      },
    },
    estimateData: {
      hours: 1.5,
      materials: [{ name: 'Zapalovací elektroda Vaillant', quantity: 1, unitPrice: 850, vatRate: 21 }],
      travelKm: 6,
      needsNextVisit: false,
    } as any,
  },

  // ── 5. Práce probíhá — dokončit ──
  {
    id: 'demo-5',
    name: 'Výměna sprchové baterie',
    referenceNumber: 'ZR-DEMO-005',
    insurance: 'Pojišťovna',
    category: '01. Plumber',
    customerAddress: 'Šafaříkova 7',
    customerCity: 'Praha 2',
    customerName: 'Tomáš Horák',
    customerPhone: '+420777000005',
    urgency: 'normal',
    createdAt: new Date().toISOString(),
    status: 'praca',
    techPhase: 'working',
    crmStep: 6,
    scheduledDate: today(),
    scheduledTime: '11:00 - 13:00',
    country: 'CZ',
    subject: 'Sprchová baterie teče i v zavřeném stavu. Potřeba výměny celé baterie.',
    distance: 3,
    durationMinutes: 8,
    finalPhotosUploaded: true,
    photos: [
      { id: 'p1', url: '', type: 'before', caption: 'Poškozená baterie', uploadedAt: new Date().toISOString() },
      { id: 'p2', url: '', type: 'damage', caption: 'Detail koroze', uploadedAt: new Date().toISOString() },
    ],
    customFields: {
      client_diagnostic: {
        description: 'Sprchová baterie teče i v zavřeném stavu. Problém asi měsíc. Kape na podlahu.',
        photos_count: 2,
      },
    },
    estimateData: {
      hours: 1,
      materials: [{ name: 'Sprchová baterie Grohe', quantity: 1, unitPrice: 2200, vatRate: 21 }],
      travelKm: 3,
      needsNextVisit: false,
    } as any,
  },

  // ── 6. Fakturace — vygenerovat fakturu ──
  {
    id: 'demo-inv',
    name: 'Oprava topení — fakturace',
    referenceNumber: 'ZR-DEMO-INV',
    insurance: 'Pojišťovna',
    category: '02. Heating',
    customerAddress: 'Budečská 9',
    customerCity: 'Praha 2',
    customerName: 'Karel Černý',
    customerPhone: '+420777000008',
    urgency: 'normal',
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    status: 'zuctovanie',
    techPhase: 'settlement_review',
    crmStep: 9,
    scheduledDate: today(),
    scheduledTime: '07:00 - 09:00',
    country: 'CZ',
    subject: 'Radiátor v ložnici netopí. Oprava dokončena — čeká na vystavení faktury.',
    distance: 7,
    durationMinutes: 16,
    finalPhotosUploaded: true,
    photos: [
      { id: 'inv-p1', url: '', type: 'before', caption: 'Radiátor před opravou', uploadedAt: new Date(Date.now() - 43200000).toISOString() },
      { id: 'inv-p2', url: '', type: 'after', caption: 'Nová termostatická hlavice', uploadedAt: new Date(Date.now() - 36000000).toISOString() },
    ],
    approvedWorkPrice: 1350,
    approvedMaterialPrice: 450,
    approvedTravelPrice: 830,
    approvedTotal: 2630,
    customFields: {
      pending_settlement: {
        hours: 1.5,
        km: 14,
        materials: [
          { id: 'm1', name: 'Termostatická hlavice Danfoss', quantity: 1, pricePerUnit: 450, type: 'heating', unit: 'ks', payer: 'pojistovna' },
        ],
        visitDate: today(),
        arrivalTime: '07:15',
        departureTime: '08:45',
      },
      confirmed_settlement: {
        hours: 1.5,
        km: 14,
        materials: [{ name: 'Termostatická hlavice Danfoss', qty: 1, price: 450 }],
        work_price: 1350,
        material_price: 450,
        travel_price: 830,
        total: 2630,
      },
      protocol_history: [
        {
          visitNumber: 1,
          type: 'final',
          submittedAt: new Date(Date.now() - 36000000).toISOString(),
          workDescription: 'Výměna termostatické hlavice na radiátoru v ložnici. Odvzdušnění celého okruhu.',
          materials: [{ name: 'Termostatická hlavice Danfoss', quantity: 1, unitPrice: 450 }],
        },
      ],
    },
  },

  // ── 7. Dokončeno — uhrazeno (historie) ──
  {
    id: 'demo-6',
    name: 'Oprava vodovodního potrubí',
    referenceNumber: 'ZR-DEMO-006',
    insurance: 'Pojišťovna',
    category: '01. Plumber',
    customerAddress: 'Jugoslávská 22',
    customerCity: 'Praha 2',
    customerName: 'Jiří Procházka',
    customerPhone: '+420777000006',
    urgency: 'normal',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    status: 'uhradene',
    techPhase: 'departed',
    crmStep: 13,
    scheduledDate: yesterday(),
    scheduledTime: '09:00 - 11:00',
    country: 'CZ',
    subject: 'Prasklé potrubí pod dřezem. Oprava dokončena, faktura uhrazena.',
    distance: 10,
    durationMinutes: 22,
    finalPhotosUploaded: true,
    photos: [
      { id: 'done-p1', url: '', type: 'before', caption: 'Prasklé potrubí', uploadedAt: new Date(Date.now() - 86400000).toISOString() },
      { id: 'done-p2', url: '', type: 'after', caption: 'Opravené potrubí', uploadedAt: new Date(Date.now() - 82800000).toISOString() },
    ],
    approvedWorkPrice: 1800,
    approvedMaterialPrice: 320,
    approvedTravelPrice: 830,
    approvedTotal: 2950,
    paymentStatus: 'paid',
    customFields: {
      protocol_history: [
        {
          visitNumber: 1,
          type: 'final',
          submittedAt: new Date(Date.now() - 82800000).toISOString(),
          workDescription: 'Výměna prasklého úseku potrubí pod dřezem. Připojení nových fitinek, zkouška těsnosti.',
          materials: [{ name: 'Cu potrubí 15mm 2m', quantity: 1, unitPrice: 180 }, { name: 'Fitinky sada', quantity: 1, unitPrice: 140 }],
        },
      ],
    },
  },
]
