/**
 * Material catalog — hierarchical: name → brands[] + types[]
 * Used for autocomplete suggestions in EstimateFormModal.
 *
 * Category codes match SPECIALIZATIONS from constants.ts (e.g. '01' = Plumber).
 * Technician can always override / type custom values — these are suggestions only.
 *
 * Structure:
 *   MaterialItem { name, brands?, types? }
 *   - name: druh materiálu ("Sifón umývadlový")
 *   - brands: dostupné značky pre tento druh (["Alcaplast", "HL", "Viega"])
 *   - types: dostupné typy/rozmery (["DN32", "DN40", "DN50"])
 */

export interface MaterialItem {
  name: string
  brands?: string[]
  types?: string[]
}

/** Flat suggestion for name autocomplete dropdown */
export interface MaterialSuggestion {
  name: string
  brand?: string
}

/** Extract 2-digit code from category string like "01. Plumber" */
export function getCategoryCode(category: string): string {
  const match = category.match(/^(\d{2})/)
  return match ? match[1] : ''
}

/**
 * Get flat name suggestions for autocomplete.
 * Returns unique names from category-specific + universal items.
 * Pass lang='cz' for Czech translations.
 */
export function getMaterialSuggestions(category: string, lang?: string): MaterialSuggestion[] {
  const code = getCategoryCode(category)
  const rawItems = [...(MATERIAL_CATALOG[code] || []), ...UNIVERSAL_MATERIALS]
  const items = lang === 'cz' ? rawItems.map(translateItem) : rawItems
  return items.map(i => ({ name: i.name, brand: i.brands?.[0] }))
}

/**
 * Filter suggestions by search query.
 */
export function filterSuggestions(suggestions: MaterialSuggestion[], query: string): MaterialSuggestion[] {
  if (!query || query.length < 1) return suggestions
  const q = stripDiacritics(query)
  return suggestions.filter(
    s => stripDiacritics(s.name).includes(q) || (s.brand && stripDiacritics(s.brand).includes(q))
  )
}

/**
 * Get brand suggestions for a specific material name in a category.
 */
export function getBrandSuggestions(category: string, materialName: string, lang?: string): string[] {
  const code = getCategoryCode(category)
  const rawItems = [...(MATERIAL_CATALOG[code] || []), ...UNIVERSAL_MATERIALS]
  const items = lang === 'cz' ? rawItems.map(translateItem) : rawItems
  const q = stripDiacritics(materialName)
  // Find exact or closest match
  const exact = items.find(i => stripDiacritics(i.name) === q)
  if (exact?.brands) return exact.brands
  // Partial match — merge brands from all matching items
  const brands = new Set<string>()
  items.filter(i => stripDiacritics(i.name).includes(q) || q.includes(stripDiacritics(i.name)))
    .forEach(i => i.brands?.forEach(b => brands.add(b)))
  return Array.from(brands)
}

/**
 * Get type/size suggestions for a specific material name in a category.
 */
export function getTypeSuggestions(category: string, materialName: string, lang?: string): string[] {
  const code = getCategoryCode(category)
  const rawItems = [...(MATERIAL_CATALOG[code] || []), ...UNIVERSAL_MATERIALS]
  const items = lang === 'cz' ? rawItems.map(translateItem) : rawItems
  const q = stripDiacritics(materialName)
  const exact = items.find(i => stripDiacritics(i.name) === q)
  if (exact?.types) return exact.types
  const types = new Set<string>()
  items.filter(i => stripDiacritics(i.name).includes(q) || q.includes(stripDiacritics(i.name)))
    .forEach(i => i.types?.forEach(t => types.add(t)))
  return Array.from(types)
}

// ═══════════════════════════════════════════════════════════════════
// SK → CZ TRANSLATION (material names + types)
// ═══════════════════════════════════════════════════════════════════

/** Word-level replacements for SK→CZ localization */
const SK_CZ_WORDS: [RegExp, string][] = [
  // Specific multi-word patterns first
  [/\bTesniaca pasta \+ konope\b/g, 'Těsnicí pasta + konopí'],
  [/\bs prepadom\b/g, 's přepadem'],
  [/\bbez prepadu\b/g, 'bez přepadu'],
  [/\bpriestorovo úsporný\b/g, 'prostorově úsporný'],
  [/\bautomatický click-clack\b/g, 'automatický click-clack'],
  [/\bnízky 52mm\b/g, 'nízký 52mm'],
  [/\bnízky 60mm\b/g, 'nízký 60mm'],
  [/\blineárny žľab\b/g, 'lineární žlab'],
  [/\bsuchá zápachová uzávera\b/g, 'suchá zápachová uzávěra'],
  [/\bnerez mriežka\b/g, 'nerez mřížka'],
  [/\bs filtrom\b/g, 's filtrem'],
  [/\bna plyn \(žltá\)\b/g, 'na plyn (žlutá)'],
  [/\bsada rôzne\b/g, 'sada různé'],
  [/\bpomalé sklápanie\b/g, 'pomalé sklápění'],
  [/\bbočný prívod\b/g, 'boční přívod'],
  [/\bspodný prívod\b/g, 'spodní přívod'],
  [/\bjednoduché splachovanie\b/g, 'jednoduché splachování'],
  [/\bdvojité splachovanie\b/g, 'dvojité splachování'],
  [/\bstop tlačidlo\b/g, 'stop tlačítko'],
  [/\bhĺbkové splachovanie\b/g, 'hluboké splachování'],
  [/\bs výsuvnou sprškou\b/g, 's výsuvnou sprškou'],
  [/\bvysoký oblúk\b/g, 'vysoký oblouk'],
  [/\bnízky oblúk\b/g, 'nízký oblouk'],
  [/\bfiltrovaná voda\b/g, 'filtrovaná voda'],
  [/\bvoľne stojaca\b/g, 'volně stojící'],
  [/\búsporná\b/g, 'úsporná'],
  [/\bdažďová\b/g, 'dešťová'],
  [/\bs mydelničkou\b/g, 's mýdelničkou'],
  [/\bzvislý\b/g, 'svislý'],
  [/\bvodorovný\b/g, 'vodorovný'],
  [/\bpre čistú vodu\b/g, 'pro čistou vodu'],
  [/\bpre špinavú vodu\b/g, 'pro špinavou vodu'],
  [/\bpre TUV\b/g, 'pro TÚV'],
  [/\bstudená voda\b/g, 'studená voda'],
  [/\bteplá voda\b/g, 'teplá voda'],
  [/\bsamočistiaci\b/g, 'samočisticí'],
  [/\bvýmenný\b/g, 'výměnný'],
  [/\bpod obklad\b/g, 'pod obklad'],
  [/\bna omietku\b/g, 'na omítku'],
  [/\bpod omietku\b/g, 'pod omítku'],
  [/\bstaviteľná\b/g, 'stavitelná'],
  [/\bnormálne zatvorený\b/g, 'normálně zavřený'],
  [/\bnormálne otvorený\b/g, 'normálně otevřený'],
  [/\bbezdrôtový\b/g, 'bezdrátový'],
  [/\bpre kotol\b/g, 'pro kotel'],
  [/\bpre klímu\b/g, 'pro klima'],
  [/\bpre sporák\b/g, 'pro sporák'],
  [/\bpre PB bombu\b/g, 'pro PB bombu'],
  [/\bzemný plyn\b/g, 'zemní plyn'],
  [/\bna kľúč\b/g, 'na klíč'],
  [/\bna cylindrickú vložku\b/g, 'na cylindrickou vložku'],
  [/\bviacbodový\b/g, 'vícebodový'],
  [/\bna rozete\b/g, 'na rozetě'],
  [/\bna štítku\b/g, 'na štítku'],
  [/\bbiela\b/g, 'bílá'],
  [/\bbiely\b/g, 'bílý'],
  [/\bbiele\b/g, 'bílé'],
  [/\bčierna\b/g, 'černá'],
  [/\bčierny\b/g, 'černý'],
  [/\bšedý\b/g, 'šedý'],
  [/\bžltá\b/g, 'žlutá'],
  [/\bčervená\b/g, 'červená'],
  [/\bhnedý\b/g, 'hnědý'],
  // Single-word patterns
  [/\bumývadlový\b/g, 'umyvadlový'],
  [/\bumývadlová\b/g, 'umyvadlová'],
  [/\bdrezový\b/g, 'dřezový'],
  [/\bdrezová\b/g, 'dřezová'],
  [/\bvaňový\b/g, 'vanový'],
  [/\bvaňová\b/g, 'vanová'],
  [/\bsprchový\b/g, 'sprchový'],
  [/\bsprchová\b/g, 'sprchová'],
  [/\bpodlahový\b/g, 'podlahový'],
  [/\bpráčkový\b/g, 'pračkový'],
  [/\bkondenzačný\b/g, 'kondenzační'],
  [/\bpodomietkový\b/g, 'podomítkový'],
  [/\bnástenný\b/g, 'nástěnný'],
  [/\bkombinovaný\b/g, 'kombinovaný'],
  [/\bsamouzatvárací\b/g, 'samouzavírací'],
  [/\bpriama\b/g, 'přímá'],
  [/\bpriamy\b/g, 'přímý'],
  [/\brohový\b/g, 'rohový'],
  [/\brohová\b/g, 'rohová'],
  [/\bnastaviteľný\b/g, 'nastavitelný'],
  [/\bjednotuchý\b/g, 'jednoduchý'],
  [/\bjednoduchý\b/g, 'jednoduchý'],
  [/\bdvojitý\b/g, 'dvojitý'],
  [/\bmosadzný\b/g, 'mosazný'],
  [/\bchrómový\b/g, 'chromový'],
  [/\bchrómová\b/g, 'chromová'],
  [/\bantibakteriálne\b/g, 'antibakteriální'],
  [/\btermostatická\b/g, 'termostatická'],
  [/\btermostatický\b/g, 'termostatický'],
  [/\bštandardné\b/g, 'standardní'],
  [/\bštandardná\b/g, 'standardní'],
  [/\bštandard\b/g, 'standard'],
  [/\buniverzálny\b/g, 'univerzální'],
  [/\buniverzálna\b/g, 'univerzální'],
  [/\buniverzálne\b/g, 'univerzální'],
  [/\bsanitárny\b/g, 'sanitární'],
  [/\bprotipožiarny\b/g, 'protipožární'],
  [/\bprotipožiarna\b/g, 'protipožární'],
  [/\bnízkoexpanzná\b/g, 'nízkoexpanzní'],
  [/\bpištolová\b/g, 'pistolová'],
  [/\bsamorezy\b/g, 'samořezy'],
  [/\bčierna\b/g, 'černá'],
  [/\bnitrilové\b/g, 'nitrilové'],
  [/\bpracovné\b/g, 'pracovní'],
  [/\bSifón\b/g, 'Sifon'],
  [/\bsifón\b/g, 'sifon'],
  [/\bHadica\b/g, 'Hadice'],
  [/\bVentil\b/g, 'Ventil'],
  [/\bTesnenie\b/g, 'Těsnění'],
  [/\btesnenie\b/g, 'těsnění'],
  [/\bTeflónová\b/g, 'Teflonová'],
  [/\bteflónová\b/g, 'teflonová'],
  [/\bGumové\b/g, 'Gumové'],
  [/\bkrúžok\b/g, 'kroužek'],
  [/\bKrúžok\b/g, 'Kroužek'],
  [/\bManžeta\b/g, 'Manžeta'],
  [/\bObjímka\b/g, 'Objímka'],
  [/\bopravná\b/g, 'opravná'],
  [/\bRýchlospojka\b/g, 'Rychlospojka'],
  [/\bsedátko\b/g, 'sedátko'],
  [/\bnapúšťací\b/g, 'napouštěcí'],
  [/\bvypúšťací\b/g, 'vypouštěcí'],
  [/\bmechanizmus\b/g, 'mechanismus'],
  [/\bovládacie\b/g, 'ovládací'],
  [/\btesniaci\b/g, 'těsnicí'],
  [/\bmanžeta\b/g, 'manžeta'],
  [/\bpripojovacia\b/g, 'připojovací'],
  [/\bnádržka\b/g, 'nádržka'],
  [/\bnástennná\b/g, 'nástěnná'],
  [/\bmisa\b/g, 'mísa'],
  [/\bzávesná\b/g, 'závěsná'],
  [/\bstojaca\b/g, 'stojací'],
  [/\binštalačný\b/g, 'instalační'],
  [/\bBatéria\b/g, 'Baterie'],
  [/\bbatéria\b/g, 'baterie'],
  [/\bpáková\b/g, 'páková'],
  [/\bstojančeková\b/g, 'stojánková'],
  [/\bsenzorová\b/g, 'senzorová'],
  [/\bKartuša\b/g, 'Kartuše'],
  [/\bkeramická\b/g, 'keramická'],
  [/\bPerlator\b/g, 'Perlátor'],
  [/\bvnútorný\b/g, 'vnitřní'],
  [/\bvnútorná\b/g, 'vnitřní'],
  [/\bvonkajší\b/g, 'vnější'],
  [/\bvonkajšia\b/g, 'vnější'],
  [/\bručná\b/g, 'ruční'],
  [/\bhlavová\b/g, 'hlavová'],
  [/\bokrúhla\b/g, 'kulatá'],
  [/\bštvorcová\b/g, 'čtvercová'],
  [/\bBojler\b/g, 'Bojler'],
  [/\bPrietokový\b/g, 'Průtokový'],
  [/\bprietokový\b/g, 'průtokový'],
  [/\bZásobníkový\b/g, 'Zásobníkový'],
  [/\bponorné\b/g, 'ponorné'],
  [/\bcirkulačné\b/g, 'cirkulační'],
  [/\bČerpadlo\b/g, 'Čerpadlo'],
  [/\bkalové\b/g, 'kalové'],
  [/\bVodomer\b/g, 'Vodoměr'],
  [/\bsuchobežný\b/g, 'suchoběžný'],
  [/\bmokrobežný\b/g, 'mokroběžný'],
  [/\bFilter\b/g, 'Filtr'],
  [/\bfilter\b/g, 'filtr'],
  [/\bmechanický\b/g, 'mechanický'],
  [/\bRevízne\b/g, 'Revizní'],
  [/\brevízne\b/g, 'revizní'],
  [/\bdvierka\b/g, 'dvířka'],
  [/\bprechodka\b/g, 'přechodka'],
  [/\bPrechodka\b/g, 'Přechodka'],
  [/\bstenová doska\b/g, 'stěnová deska'],
  [/\buzáver\b/g, 'uzávěr'],
  [/\bUzáver\b/g, 'Uzávěr'],
  [/\bspojka\b/g, 'spojka'],
  [/\bSpojka\b/g, 'Spojka'],
  [/\bkoleno\b/g, 'koleno'],
  [/\bKoleno\b/g, 'Koleno'],
  [/\bodbočka\b/g, 'odbočka'],
  [/\bredukcia\b/g, 'redukce'],
  [/\bRedukcia\b/g, 'Redukce'],
  [/\bzasúvka\b/g, 'zasuvka'],
  [/\bčistiaci kus\b/g, 'čisticí kus'],
  [/\bČistiaci kus\b/g, 'Čisticí kus'],
  [/\bprechod\b/g, 'přechod'],
  [/\bPrechod\b/g, 'Přechod'],
  [/\brúra\b/g, 'trubka'],
  [/\bRúra\b/g, 'Trubka'],
  [/\brúrka\b/g, 'trubka'],
  [/\bRúrka\b/g, 'Trubka'],
  // Heating
  [/\bRadiátor\b/g, 'Radiátor'],
  [/\bradiátor\b/g, 'radiátor'],
  [/\bpanelový\b/g, 'panelový'],
  [/\bkúpeľňový\b/g, 'koupelnový'],
  [/\brebríkový\b/g, 'žebříkový'],
  [/\bčlánkový\b/g, 'článkový'],
  [/\bhliníkový\b/g, 'hliníkový'],
  [/\bliatinový\b/g, 'litinový'],
  [/\bbimetalový\b/g, 'bimetalový'],
  [/\bOdvzdušňovací\b/g, 'Odvzdušňovací'],
  [/\bautomatický\b/g, 'automatický'],
  [/\bručný\b/g, 'ruční'],
  [/\bkľúčik\b/g, 'klíček'],
  [/\bzátka\b/g, 'zátka'],
  [/\bľavá\b/g, 'levá'],
  [/\bpravá\b/g, 'pravá'],
  [/\bKonzola\b/g, 'Konzola'],
  [/\bSpájka\b/g, 'Pájka'],
  [/\bspájka\b/g, 'pájka'],
  [/\bmäkká\b/g, 'měkká'],
  [/\bbezólová\b/g, 'bezolovnatá'],
  [/\bTavidlo\b/g, 'Tavidlo'],
  [/\bna mäkké spájkovanie\b/g, 'na měkké pájení'],
  [/\bna tvrdé spájkovanie\b/g, 'na tvrdé pájení'],
  [/\bIzolácia\b/g, 'Izolace'],
  [/\bizolácia\b/g, 'izolace'],
  [/\bExpanzná nádoba\b/g, 'Expanzní nádoba'],
  [/\bexpanzná nádoba\b/g, 'expanzní nádoba'],
  [/\bMembrána\b/g, 'Membrána'],
  [/\bdo expanznej nádoby\b/g, 'do expanzní nádoby'],
  [/\bObehové\b/g, 'Oběhové'],
  [/\bobehové\b/g, 'oběhové'],
  [/\bčerpadlo\b/g, 'čerpadlo'],
  [/\bBezpečnostný\b/g, 'Bezpečnostní'],
  [/\bbezpečnostný\b/g, 'bezpečnostní'],
  [/\bBezpečnostná\b/g, 'Bezpečnostní'],
  [/\bbezpečnostná\b/g, 'bezpečnostní'],
  [/\bskupina\b/g, 'skupina'],
  [/\bPlniaci\b/g, 'Plnicí'],
  [/\bVypúšťací\b/g, 'Vypouštěcí'],
  [/\bkohút\b/g, 'kohout'],
  [/\bKohút\b/g, 'Kohout'],
  [/\bRozdeľovač\b/g, 'Rozdělovač'],
  [/\bServopohon\b/g, 'Servopohon'],
  [/\bPriestorový\b/g, 'Prostorový'],
  [/\bpriestorový\b/g, 'prostorový'],
  [/\btermostat\b/g, 'termostat'],
  [/\bdigitálny\b/g, 'digitální'],
  [/\bprogramovateľný\b/g, 'programovatelný'],
  [/\bMagnetický\b/g, 'Magnetický'],
  [/\bNemrznúca\b/g, 'Nemrznoucí'],
  [/\bnemrznúca\b/g, 'nemrznoucí'],
  [/\bzmes\b/g, 'směs'],
  [/\bInhibítor\b/g, 'Inhibitor'],
  [/\bkorózie\b/g, 'koroze'],
  // Gasman
  [/\bPlynová\b/g, 'Plynová'],
  [/\bplynový\b/g, 'plynový'],
  [/\bPlynový\b/g, 'Plynový'],
  [/\bRegulátor\b/g, 'Regulátor'],
  [/\bTermočlánok\b/g, 'Termočlánek'],
  [/\btryska\b/g, 'tryska'],
  [/\bZapaľovač\b/g, 'Zapalovač'],
  [/\bzapaľovač\b/g, 'zapalovač'],
  [/\bsporáka\b/g, 'sporáku'],
  [/\bOvládací\b/g, 'Ovládací'],
  [/\bHorák\b/g, 'Hořák'],
  [/\bhorák\b/g, 'hořák'],
  [/\bmalý\b/g, 'malý'],
  [/\bstredný\b/g, 'střední'],
  [/\bveľký\b/g, 'velký'],
  [/\bpomocný\b/g, 'pomocný'],
  [/\boceľová\b/g, 'ocelová'],
  [/\bDetektor\b/g, 'Detektor'],
  [/\búniku\b/g, 'úniku'],
  [/\bElektromagnetický\b/g, 'Elektromagnetický'],
  // Boiler
  [/\bZapaľovacia\b/g, 'Zapalovací'],
  [/\belektróda\b/g, 'elektroda'],
  [/\bIonizačná\b/g, 'Ionizační'],
  [/\bjednotka\b/g, 'jednotka'],
  [/\btrafo\b/g, 'trafo'],
  [/\barmatúra\b/g, 'armatura'],
  [/\bArmatúra\b/g, 'Armatura'],
  [/\bVýmenník\b/g, 'Výměník'],
  [/\bvýmenník\b/g, 'výměník'],
  [/\bprimárny\b/g, 'primární'],
  [/\bsekundárny\b/g, 'sekundární'],
  [/\bdoskový\b/g, 'deskový'],
  [/\bTrojcestný\b/g, 'Trojcestný'],
  [/\bkomplet\b/g, 'komplet'],
  [/\blen motor\b/g, 'jen motor'],
  [/\blen telo\b/g, 'jen těleso'],
  [/\bSnímač\b/g, 'Snímač'],
  [/\bteploty\b/g, 'teploty'],
  [/\bspiatočka\b/g, 'zpátečka'],
  [/\bzásobník\b/g, 'zásobník'],
  [/\btlaku\b/g, 'tlaku'],
  [/\bPresostat\b/g, 'Presostat'],
  [/\bvzduchu\b/g, 'vzduchu'],
  [/\bvody\b/g, 'vody'],
  [/\bdymu\b/g, 'kouře'],
  [/\bRiadiaca doska\b/g, 'Řídicí deska'],
  [/\briadiaca doska\b/g, 'řídicí deska'],
  [/\bDisplej\b/g, 'Displej'],
  [/\bpanel\b/g, 'panel'],
  [/\bVentilátor\b/g, 'Ventilátor'],
  [/\bturbína\b/g, 'turbína'],
  [/\bKondenzačný\b/g, 'Kondenzační'],
  [/\bDymovod\b/g, 'Kouřovod'],
  [/\bkoncovka fasádna\b/g, 'koncovka fasádní'],
  [/\bkoncovka strešná\b/g, 'koncovka střešní'],
  [/\brevízny\b/g, 'revizní'],
  [/\bTesnenie výmenníka\b/g, 'Těsnění výměníku'],
  [/\bO-krúžky\b/g, 'O-kroužky'],
  [/\bFilter kotlovej vody\b/g, 'Filtr kotlové vody'],
  // Electric boiler
  [/\bVyhrievacie teleso\b/g, 'Topné těleso'],
  [/\bsuchý ohrev\b/g, 'suchý ohřev'],
  [/\bprírubové\b/g, 'přírubové'],
  [/\bTermostat\b/g, 'Termostat'],
  [/\btyčový\b/g, 'tyčový'],
  [/\bkapilárkový\b/g, 'kapilárový'],
  [/\belektronický\b/g, 'elektronický'],
  [/\bAnódová tyč\b/g, 'Anodová tyč'],
  [/\btitanová elektronická\b/g, 'titanová elektronická'],
  [/\bTesnenie príruby\b/g, 'Těsnění příruby'],
  [/\bjednofázový\b/g, 'jednofázový'],
  [/\btrojfázový\b/g, 'třífázový'],
  // Thermal pumps
  [/\bKompresor\b/g, 'Kompresor'],
  [/\btepelného čerpadla\b/g, 'tepelného čerpadla'],
  [/\bChladivo\b/g, 'Chladivo'],
  [/\bExpanzný ventil\b/g, 'Expanzní ventil'],
  [/\bŠtvorcestný\b/g, 'Čtyřcestný'],
  [/\bvýstup\b/g, 'výstup'],
  [/\bRiadiaca doska TČ\b/g, 'Řídicí deska TČ'],
  [/\bVentilátor vonkajšej jednotky\b/g, 'Ventilátor venkovní jednotky'],
  [/\bElektropatróna záložná\b/g, 'Elektropatrona záložní'],
  [/\bAkumulačná nádoba\b/g, 'Akumulační nádoba'],
  // Solar
  [/\bSolárny\b/g, 'Solární'],
  [/\bsolárny\b/g, 'solární'],
  [/\bSolárna\b/g, 'Solární'],
  [/\bSolárne\b/g, 'Solární'],
  [/\btermický plochý\b/g, 'termický plochý'],
  [/\btermický vákuový\b/g, 'termický vakuový'],
  [/\bfotovoltaický\b/g, 'fotovoltaický'],
  [/\bhybridný\b/g, 'hybridní'],
  [/\bBatériový\b/g, 'Bateriový'],
  [/\bOptimizér\b/g, 'Optimizér'],
  [/\bMontážna konštrukcia\b/g, 'Montážní konstrukce'],
  [/\bšikmá strecha\b/g, 'šikmá střecha'],
  [/\brovná strecha\b/g, 'rovná střecha'],
  [/\bfasáda\b/g, 'fasáda'],
  [/\bzem\b/g, 'zem'],
  // Unblocking
  [/\bČistiaci kábel\b/g, 'Čisticí kabel'],
  [/\bČistiacia hlavica\b/g, 'Čisticí hlavice'],
  [/\bšípová\b/g, 'šípová'],
  [/\breťazová\b/g, 'řetězová'],
  [/\bkoreňová\b/g, 'kořenová'],
  [/\bguľová\b/g, 'kulová'],
  [/\bChemický čistič\b/g, 'Chemický čistič'],
  [/\bEnzymatický čistič\b/g, 'Enzymatický čistič'],
  [/\bodpadov\b/g, 'odpadů'],
  [/\bZvon na odpady\b/g, 'Zvon na odpady'],
  [/\bgumový\b/g, 'gumový'],
  [/\bvýmena\b/g, 'výměna'],
  [/\bVysokotlaková\b/g, 'Vysokotlaková'],
  [/\brotačná\b/g, 'rotační'],
  [/\bFrézovacie\b/g, 'Frézovací'],
  [/\bškrabacia\b/g, 'škrabací'],
  [/\bRevízna šachta\b/g, 'Revizní šachta'],
  [/\bPoklop\b/g, 'Poklop'],
  // Electrician
  [/\bIstič\b/g, 'Jistič'],
  [/\bistič\b/g, 'jistič'],
  [/\bPrúdový chránič\b/g, 'Proudový chránič'],
  [/\bs istením\b/g, 's jištěním'],
  [/\bPrepäťová ochrana\b/g, 'Přepěťová ochrana'],
  [/\bZásuvka\b/g, 'Zásuvka'],
  [/\bs prepäťovou ochranou\b/g, 's přepěťovou ochranou'],
  [/\brámček\b/g, 'rámeček'],
  [/\bRámček\b/g, 'Rámeček'],
  [/\bsilová\b/g, 'silová'],
  [/\bVypínač\b/g, 'Vypínač'],
  [/\bjednopólový\b/g, 'jednopólový'],
  [/\bsériový\b/g, 'sériový'],
  [/\bstriedavý\b/g, 'střídavý'],
  [/\bschodiskový\b/g, 'schodišťový'],
  [/\bkrížový\b/g, 'křížový'],
  [/\btlačidlo\b/g, 'tlačítko'],
  [/\bzvonček\b/g, 'zvonek'],
  [/\bstmievač\b/g, 'stmívač'],
  [/\bkrémový\b/g, 'krémový'],
  [/\bantracit\b/g, 'antracit'],
  [/\bnásobný\b/g, 'násobný'],
  [/\bKábel\b/g, 'Kabel'],
  [/\bkábel\b/g, 'kabel'],
  [/\bplochý\b/g, 'plochý'],
  [/\bgumový\b/g, 'gumový'],
  [/\bVodič\b/g, 'Vodič'],
  [/\bElektroinštalačná rúrka\b/g, 'Elektroinstalační trubka'],
  [/\btuhá\b/g, 'tuhá'],
  [/\bohybná\b/g, 'ohebná'],
  [/\bChránička\b/g, 'Chránička'],
  [/\bKrabica\b/g, 'Krabice'],
  [/\bprístrojová\b/g, 'přístrojová'],
  [/\bhĺbková\b/g, 'hluboká'],
  [/\bodbočná\b/g, 'odbočná'],
  [/\bRozvádzač\b/g, 'Rozváděč'],
  [/\bbytový\b/g, 'bytový'],
  [/\bsvorka\b/g, 'svorka'],
  [/\bs pákou\b/g, 's páčkou'],
  [/\bžiarovka\b/g, 'žárovka'],
  [/\bŽiarovka\b/g, 'Žárovka'],
  [/\bteplá biela\b/g, 'teplá bílá'],
  [/\bneutrálna\b/g, 'neutrální'],
  [/\bstmievateľná\b/g, 'stmívatelná'],
  [/\btrubica\b/g, 'trubice'],
  [/\bprisadený\b/g, 'přisazený'],
  [/\bzapustený\b/g, 'zapuštěný'],
  [/\breflektor\b/g, 'reflektor'],
  [/\bso senzorom\b/g, 'se senzorem'],
  [/\bbez senzora\b/g, 'bez senzoru'],
  [/\bbodovka podhľadová\b/g, 'bodovka podhledová'],
  [/\bpevná\b/g, 'pevná'],
  [/\bvýklopná\b/g, 'výklopná'],
  [/\bnikel\b/g, 'nikl'],
  [/\bpásik\b/g, 'pásek'],
  [/\bPásik\b/g, 'Pásek'],
  [/\bstudená\b/g, 'studená'],
  [/\bSvietidlo\b/g, 'Svítidlo'],
  [/\bstropné\b/g, 'stropní'],
  [/\bprisadené\b/g, 'přisazené'],
  [/\bnástenné\b/g, 'nástěnné'],
  [/\bvonkajšie\b/g, 'venkovní'],
  [/\bnúdzové\b/g, 'nouzové'],
  [/\bdo kúpeľne\b/g, 'do koupelny'],
  [/\bPohybový snímač\b/g, 'Pohybový snímač'],
  [/\bvstavaný\b/g, 'vestavěný'],
  [/\bSnímač dymu\b/g, 'Detektor kouře'],
  [/\bZvonček\b/g, 'Zvonek'],
  [/\bdrôtový\b/g, 'drátový'],
  [/\bvideovrátnik\b/g, 'videovrátný'],
  [/\bStýkač\b/g, 'Stykač'],
  [/\bČasový spínač\b/g, 'Časový spínač'],
  [/\bschodiskový automat\b/g, 'schodišťový automat'],
  [/\banalógový\b/g, 'analogový'],
  [/\btýždenný\b/g, 'týdenní'],
  [/\bSťahovacia páska\b/g, 'Stahovací páska'],
  [/\bsťahovacia páska\b/g, 'stahovací páska'],
  [/\bUzemnenie\b/g, 'Uzemnění'],
  [/\buzemňovacia\b/g, 'uzemňovací'],
  [/\bekvipotenciálna\b/g, 'ekvipotenciální'],
  // Electronics
  [/\bizbová\b/g, 'pokojová'],
  [/\bvonkajšia\b/g, 'venkovní'],
  [/\bsatelitná\b/g, 'satelitní'],
  [/\bzosilňovač\b/g, 'zesilovač'],
  [/\bKoaxiálny\b/g, 'Koaxiální'],
  // Aircon
  [/\bRozbehovací kondenzátor\b/g, 'Rozběhový kondenzátor'],
  [/\bDrenážne\b/g, 'Drenážní'],
  [/\bKommunikačný\b/g, 'Komunikační'],
  [/\bKanál dekoratívny\b/g, 'Kanál dekorativní'],
  [/\bDržiak\b/g, 'Držák'],
  [/\bdržiak\b/g, 'držák'],
  [/\bAntivibračné\b/g, 'Antivibrační'],
  [/\bPriechodka\b/g, 'Průchodka'],
  [/\bstenová\b/g, 'stěnová'],
  [/\bČistiaci prostriedok\b/g, 'Čisticí prostředek'],
  [/\bDezinfekcia\b/g, 'Dezinfekce'],
  [/\bklímu\b/g, 'klima'],
  [/\bDiaľkový ovládač\b/g, 'Dálkový ovladač'],
  [/\bvýparníka\b/g, 'výparníku'],
  [/\bkondenzátora\b/g, 'kondenzátoru'],
  [/\bKompresorový olej\b/g, 'Kompresorový olej'],
  [/\bsušiaci\b/g, 'sušicí'],
  [/\bokruh\b/g, 'okruh'],
  // Keysmith
  [/\bCylindrická vložka\b/g, 'Cylindrická vložka'],
  [/\bs gombíkom\b/g, 's knoflíkem'],
  [/\bDverný\b/g, 'Dveřní'],
  [/\bdverný\b/g, 'dveřní'],
  [/\bDverná\b/g, 'Dveřní'],
  [/\bdverná\b/g, 'dveřní'],
  [/\bDverné\b/g, 'Dveřní'],
  [/\bdverné\b/g, 'dveřní'],
  [/\bzadlabací\b/g, 'zadlabací'],
  [/\bZámok\b/g, 'Zámek'],
  [/\bzámok\b/g, 'zámek'],
  [/\bprídavný\b/g, 'přídavný'],
  [/\bdvojzámok\b/g, 'dvojzámek'],
  [/\bKľučka\b/g, 'Klika'],
  [/\bkľučka\b/g, 'klika'],
  [/\bkľučkový\b/g, 'klikový'],
  [/\bGuľa\b/g, 'Koule'],
  [/\bguľa\b/g, 'koule'],
  [/\bguľový\b/g, 'kulový'],
  [/\bGuľový\b/g, 'Kulový'],
  [/\botočná\b/g, 'otočná'],
  [/\bRozeta\b/g, 'Rozeta'],
  [/\bŠtítok\b/g, 'Štítek'],
  [/\bslepý\b/g, 'slepý'],
  [/\bProtiplech\b/g, 'Protiplech'],
  [/\bzaoblený\b/g, 'zaoblený'],
  [/\bPánty\b/g, 'Panty'],
  [/\bpánty\b/g, 'panty'],
  [/\bnastaviteľné\b/g, 'nastavitelné'],
  [/\bDverný zatvárač\b/g, 'Dveřní zavírač'],
  [/\bhorný\b/g, 'horní'],
  [/\bpodlahový\b/g, 'podlahový'],
  [/\bskrytý\b/g, 'skrytý'],
  [/\breťazový\b/g, 'řetízkový'],
  [/\breťazová\b/g, 'řetězová'],
  [/\bpoistka\b/g, 'pojistka'],
  [/\bKukátko\b/g, 'Kukátko'],
  [/\bširoký uhol\b/g, 'široký úhel'],
  [/\bElektrický zámok\b/g, 'Elektrický zámek'],
  [/\bsamozatváracie\b/g, 'samozavírací'],
  [/\bprotipožiarne\b/g, 'protipožární'],
  [/\bKľúč\b/g, 'Klíč'],
  [/\bkľúč\b/g, 'klíč'],
  [/\bduplikát\b/g, 'duplikát'],
  [/\bsystémový\b/g, 'systémový'],
  // Roof
  [/\bŠkridla\b/g, 'Taška'],
  [/\bškridla\b/g, 'taška'],
  [/\bbetónová\b/g, 'betonová'],
  [/\bhrebenáčová\b/g, 'hřebenáčová'],
  [/\bokrajová\b/g, 'okrajová'],
  [/\bvetracia\b/g, 'větrací'],
  [/\bTrapézový plech\b/g, 'Trapézový plech'],
  [/\bpozinkovaný\b/g, 'pozinkovaný'],
  [/\blakovaný\b/g, 'lakovaný'],
  [/\bŠindeľ\b/g, 'Šindel'],
  [/\bbitúmenový\b/g, 'bitumenový'],
  [/\barchitektonický\b/g, 'architektonický'],
  [/\bStrešná fólia\b/g, 'Střešní fólie'],
  [/\bparopriepustná\b/g, 'paropropustná'],
  [/\bparozábrana\b/g, 'parozábrana'],
  [/\bdifúzna\b/g, 'difúzní'],
  [/\bStrešná lata\b/g, 'Střešní lať'],
  [/\bKontralata\b/g, 'Kontralatě'],
  [/\bIzolácia strešná\b/g, 'Izolace střešní'],
  [/\bmedzi krokvy\b/g, 'mezi krokve'],
  [/\bpod krokvy\b/g, 'pod krokve'],
  [/\bOdkvapový žľab\b/g, 'Okapový žlab'],
  [/\bŽľabový\b/g, 'Žlabový'],
  [/\bžľabový\b/g, 'žlabový'],
  [/\bžľab\b/g, 'žlab'],
  [/\bhák\b/g, 'hák'],
  [/\broh\b/g, 'roh'],
  [/\bkotlík\b/g, 'kotlík'],
  [/\bdlhý\b/g, 'dlouhý'],
  [/\bkrátky\b/g, 'krátký'],
  [/\bZvod\b/g, 'Svod'],
  [/\bzvod\b/g, 'svod'],
  [/\bZvodové\b/g, 'Svodové'],
  [/\bOplechovanie\b/g, 'Oplechování'],
  [/\bkomína\b/g, 'komínu'],
  [/\bmúru\b/g, 'zdi'],
  [/\bodkvapovej hrany\b/g, 'okapové hrany'],
  [/\bštítu\b/g, 'štítu'],
  [/\bStrešné okno\b/g, 'Střešní okno'],
  [/\bkyvné\b/g, 'kyvné'],
  [/\bvýklopno-kyvné\b/g, 'výklopně-kyvné'],
  [/\bSnehová zábrana\b/g, 'Sněhová zábrana'],
  [/\bbodová\b/g, 'bodová'],
  [/\bmriežková\b/g, 'mřížková'],
  [/\brúrková\b/g, 'trubková'],
  [/\bStrešný\b/g, 'Střešní'],
  [/\bstrešný\b/g, 'střešní'],
  [/\bStrešná\b/g, 'Střešní'],
  [/\bstrešná\b/g, 'střešní'],
  [/\bkit\b/g, 'kit'],
  [/\btmel\b/g, 'tmel'],
  [/\bBitúmenový pás\b/g, 'Bitumenový pás'],
  [/\bpodkladový\b/g, 'podkladový'],
  [/\bvrchný\b/g, 'vrchní'],
  [/\bsamolepiaci\b/g, 'samolepicí'],
  [/\bsamolepiacii\b/g, 'samolepicí'],
  // Tiles
  [/\bLepidlo na obklady\b/g, 'Lepidlo na obklady'],
  [/\brýchloschnúce\b/g, 'rychleschnoucí'],
  [/\bna veľkoformáty\b/g, 'na velkoformáty'],
  [/\bna bazény\b/g, 'na bazény'],
  [/\bŠkárovacia hmota\b/g, 'Spárovací hmota'],
  [/\bcementová\b/g, 'cementová'],
  [/\bepoxidová\b/g, 'epoxidová'],
  [/\brôzne farby\b/g, 'různé barvy'],
  [/\bPenetrácia\b/g, 'Penetrace'],
  [/\bpenetrácia\b/g, 'penetrace'],
  [/\bhĺbková\b/g, 'hloubková'],
  [/\bkontaktná\b/g, 'kontaktní'],
  [/\bHydroizolácia\b/g, 'Hydroizolace'],
  [/\bHydroizolačná\b/g, 'Hydroizolační'],
  [/\btekutá\b/g, 'tekutá'],
  [/\b1-zložková\b/g, '1-složková'],
  [/\b2-zložková\b/g, '2-složková'],
  [/\bmanžeta na rúru\b/g, 'manžeta na trubku'],
  [/\bNivelačná stierka\b/g, 'Nivelační stěrka'],
  [/\bnivelačná stierka\b/g, 'nivelační stěrka'],
  [/\bRohová lišta\b/g, 'Rohová lišta'],
  [/\bPrechodová lišta\b/g, 'Přechodová lišta'],
  [/\bvýšková\b/g, 'výšková'],
  [/\bDilatačný profil\b/g, 'Dilatační profil'],
  [/\bNivelačné kríže\b/g, 'Nivelační křížky'],
  [/\bNivelačný systém\b/g, 'Nivelační systém'],
  [/\bklipy\b/g, 'klipy'],
  [/\bkliny\b/g, 'klíny'],
  [/\bkliešte\b/g, 'kleště'],
  [/\bRezný kotúč\b/g, 'Řezný kotouč'],
  [/\bdiamantový\b/g, 'diamantový'],
  [/\bna dlažbu\b/g, 'na dlažbu'],
  [/\bna obklad\b/g, 'na obklad'],
  [/\bna porcelán\b/g, 'na porcelán'],
  [/\bDierovka\b/g, 'Diamantová vrtací korunka'],
  // Flooring
  [/\bLaminátová podlaha\b/g, 'Laminátová podlaha'],
  [/\bVinylová podlaha\b/g, 'Vinylová podlaha'],
  [/\blepená\b/g, 'lepená'],
  [/\bDrevená podlaha\b/g, 'Dřevěná podlaha'],
  [/\bmasív\b/g, 'masiv'],
  [/\bvrstvená\b/g, 'vrstvená'],
  [/\bjaseň\b/g, 'jasan'],
  [/\borech\b/g, 'ořech'],
  [/\bPodložka\b/g, 'Podložka'],
  [/\bSoklová lišta\b/g, 'Soklová lišta'],
  [/\bPrechodový profil\b/g, 'Přechodový profil'],
  [/\bschodový\b/g, 'schodový'],
  [/\bhliníkový\b/g, 'hliníkový'],
  [/\bvŕtaný\b/g, 'vrtaný'],
  [/\bna koberec\b/g, 'na koberec'],
  [/\bna parkety\b/g, 'na parkety'],
  [/\bfixačné\b/g, 'fixační'],
  [/\bkrytina\b/g, 'krytina'],
  // Painting
  [/\bInteriérová farba\b/g, 'Interiérová barva'],
  [/\bumývateľná\b/g, 'omyvatelná'],
  [/\bfarebná\b/g, 'barevná'],
  [/\bdo kuchyne\b/g, 'do kuchyně'],
  [/\bmatná\b/g, 'matná'],
  [/\bpolomatná\b/g, 'polomatná'],
  [/\bFasádna farba\b/g, 'Fasádní barva'],
  [/\bakrylová\b/g, 'akrylová'],
  [/\bsilikónová\b/g, 'silikonová'],
  [/\bsilikátová\b/g, 'silikátová'],
  [/\bEmail\/lak\b/g, 'Email/lak'],
  [/\bsyntetický\b/g, 'syntetický'],
  [/\bvodou riediteľný\b/g, 'vodou ředitelný'],
  [/\bna radiátory\b/g, 'na radiátory'],
  [/\bna kov\b/g, 'na kov'],
  [/\bna drevo\b/g, 'na dřevo'],
  [/\bna podlahu\b/g, 'na podlahu'],
  [/\bbezfarebný\b/g, 'bezbarvý'],
  [/\bantikorózny\b/g, 'antikorozní'],
  [/\blesklý\b/g, 'lesklý'],
  [/\bPenetračný náter\b/g, 'Penetrační nátěr'],
  [/\bTmel vyrovnávací\b/g, 'Tmel vyrovnávací'],
  [/\bsádrový\b/g, 'sádrový'],
  [/\bTmel akrylový\b/g, 'Tmel akrylový'],
  [/\bSádrový tmel\b/g, 'Sádrový tmel'],
  [/\bVýstužná páska\b/g, 'Výztužná páska'],
  [/\bpapierová\b/g, 'papírová'],
  [/\bsklenená\b/g, 'skleněná'],
  [/\bsamolepiaca\b/g, 'samolepicí'],
  [/\bna praskliny\b/g, 'na praskliny'],
  [/\bBrúsny papier\b/g, 'Brusný papír'],
  [/\bBrúsna mriežka\b/g, 'Brusná mřížka'],
  [/\bháčiky\b/g, 'háčky'],
  [/\bpre brúsku\b/g, 'pro brusku'],
  [/\bMaliarsky valec\b/g, 'Malířský válec'],
  [/\bpena\b/g, 'pěna'],
  [/\blak\b/g, 'lak'],
  [/\bmikrovlákno\b/g, 'mikrovlákno'],
  [/\bpolyamid\b/g, 'polyamid'],
  [/\bfasádny\b/g, 'fasádní'],
  [/\bŠtetec plochý\b/g, 'Štětec plochý'],
  [/\bMaliarska páska\b/g, 'Malířská páska'],
  [/\bpre ostré hrany\b/g, 'pro ostré hrany'],
  [/\bpre oblúky\b/g, 'pro oblouky'],
  [/\bZakrývacia fólia\b/g, 'Zakrývací fólie'],
  [/\bs páskou\b/g, 's páskou'],
  [/\bStierka nerezová\b/g, 'Stěrka nerezová'],
  [/\bŠpachtľa\b/g, 'Špachtle'],
  [/\bTapeta\b/g, 'Tapeta'],
  [/\bvliesová\b/g, 'vliesová'],
  [/\bvinylová\b/g, 'vinylová'],
  [/\brolka\b/g, 'role'],
  [/\bLepidlo na tapety\b/g, 'Lepidlo na tapety'],
  // Masonry
  [/\bTvárnica\b/g, 'Tvárnice'],
  [/\bpresná\b/g, 'přesná'],
  [/\bMalta\b/g, 'Malta'],
  [/\blepidlo na Ytong\b/g, 'lepidlo na Ytong'],
  [/\bmurárska\b/g, 'zednická'],
  [/\bvápenno-cementová\b/g, 'vápenocementová'],
  [/\bCement\b/g, 'Cement'],
  [/\bportlandský\b/g, 'portlandský'],
  [/\brýchlotuhnúci\b/g, 'rychletuhnoucí'],
  [/\bBetón\b/g, 'Beton'],
  [/\brýchly\b/g, 'rychlý'],
  [/\bsuchá zmes\b/g, 'suchá směs'],
  [/\bSDK doska\b/g, 'SDK deska'],
  [/\bimpregnovaná\b/g, 'impregnovaná'],
  [/\bzelená\b/g, 'zelená'],
  [/\bružová\b/g, 'růžová'],
  [/\bakustická\b/g, 'akustická'],
  [/\bSDK profil\b/g, 'SDK profil'],
  [/\bZáves rýchly\b/g, 'Závěs rychlý'],
  [/\bpredĺžovacia\b/g, 'prodlužovací'],
  [/\bkrížová\b/g, 'křížová'],
  [/\bSkrutka\b/g, 'Šroub'],
  [/\bskrutka\b/g, 'šroub'],
  [/\bSkrutky\b/g, 'Šrouby'],
  [/\bskrutky\b/g, 'šrouby'],
  [/\bSádrová stierka\b/g, 'Sádrová stěrka'],
  [/\bfinálna\b/g, 'finální'],
  [/\bOmietka\b/g, 'Omítka'],
  [/\bomietka\b/g, 'omítka'],
  [/\bsádrová\b/g, 'sádrová'],
  [/\bvápenná\b/g, 'vápenná'],
  [/\bštuková\b/g, 'štuková'],
  [/\bArmovacia sieťka\b/g, 'Armovací síťka'],
  [/\bperlinka\b/g, 'perlinka'],
  [/\brohová lišta s perlinkou\b/g, 'rohová lišta s perlinkou'],
  [/\bminerálna vlna\b/g, 'minerální vlna'],
  [/\bHmoždinka\b/g, 'Hmoždinka'],
  [/\bhmoždinka\b/g, 'hmoždinka'],
  [/\bHmoždinky\b/g, 'Hmoždinky'],
  [/\bhmoždinky\b/g, 'hmoždinky'],
  [/\bkovová\b/g, 'kovová'],
  [/\bplastová\b/g, 'plastová'],
  [/\bsklopná\b/g, 'sklopná'],
  [/\btalierová\b/g, 'talířová'],
  [/\bKotviaca skrutka\b/g, 'Kotevní šroub'],
  [/\bdo betónu\b/g, 'do betonu'],
  [/\bChemická kotva\b/g, 'Chemická kotva'],
  [/\bMontážna pena\b/g, 'Montážní pěna'],
  [/\bmontážna pena\b/g, 'montážní pěna'],
  [/\bPreklad\b/g, 'Překlad'],
  [/\bOSB doska\b/g, 'OSB deska'],
  // Deratization
  [/\bRodenticíd\b/g, 'Rodenticid'],
  [/\bgranulát\b/g, 'granulát'],
  [/\bpasta\b/g, 'pasta'],
  [/\bblok voskový\b/g, 'blok voskový'],
  [/\btekutý\b/g, 'tekutý'],
  [/\bDeratizačná stanica\b/g, 'Deratizační stanice'],
  [/\bna myši\b/g, 'na myši'],
  [/\bna potkany\b/g, 'na potkany'],
  [/\bPasca\b/g, 'Past'],
  [/\bpasca\b/g, 'past'],
  [/\bmechanická\b/g, 'mechanická'],
  [/\blepová\b/g, 'lepová'],
  [/\bživolovná\b/g, 'živolovná'],
  [/\bInsekticíd\b/g, 'Insekticid'],
  [/\bprášok\b/g, 'prášek'],
  [/\bgél na šváby\b/g, 'gel na šváby'],
  [/\bfumigátor\b/g, 'fumigátor'],
  [/\bkoncentrát\b/g, 'koncentrát'],
  [/\bRepelent\b/g, 'Repelent'],
  [/\bultrazvukový\b/g, 'ultrazvukový'],
  [/\bDezinfekčný prostriedok\b/g, 'Dezinfekční prostředek'],
  [/\bOchranné pomôcky\b/g, 'Ochranné pomůcky'],
  [/\brukavice\b/g, 'rukavice'],
  [/\brespirátor\b/g, 'respirátor'],
  [/\bokuliare\b/g, 'brýle'],
  [/\bochranný oblek\b/g, 'ochranný oblek'],
  [/\bTesniaci materiál na diery\b/g, 'Těsnicí materiál na díry'],
  [/\bSieťka proti hmyzu\b/g, 'Síťka proti hmyzu'],
  [/\bna okno\b/g, 'na okno'],
  [/\bna dvere\b/g, 'na dveře'],
  [/\broleta\b/g, 'roleta'],
  [/\bMriežka\b/g, 'Mřížka'],
  [/\bmriežka\b/g, 'mřížka'],
  // Water systems
  [/\bDomáca vodáreň\b/g, 'Domácí vodárna'],
  [/\bs tlakovou nádobou\b/g, 's tlakovou nádobou'],
  [/\bfrekvenčne riadená\b/g, 'frekvenčně řízená'],
  [/\bPonorné čerpadlo\b/g, 'Ponorné čerpadlo'],
  [/\bKalové čerpadlo\b/g, 'Kalové čerpadlo'],
  [/\bTlaková nádoba\b/g, 'Tlaková nádoba'],
  [/\bTlakový spínač\b/g, 'Tlakový spínač'],
  [/\bFilter na studňu\b/g, 'Filtr na studnu'],
  [/\bpiesočnatý\b/g, 'pískový'],
  [/\buhlíkový\b/g, 'uhlíkový'],
  [/\bželezitý\b/g, 'železitý'],
  [/\bdusičnanový\b/g, 'dusičnanový'],
  [/\bUV sterilizátor\b/g, 'UV sterilizátor'],
  [/\bZmäkčovač\b/g, 'Změkčovač'],
  [/\bzmäkčovač\b/g, 'změkčovač'],
  [/\bzmäkčovača\b/g, 'změkčovače'],
  [/\bSoľ\b/g, 'Sůl'],
  [/\btabletová\b/g, 'tabletová'],
  [/\bNavrtávací pás\b/g, 'Navrtávací pás'],
  [/\bŠupátkový ventil\b/g, 'Šoupátkový ventil'],
  [/\bVodomerná šachta\b/g, 'Vodoměrná šachta'],
  [/\bbetónová\b/g, 'betonová'],
  // Universal
  [/\bSilikón\b/g, 'Silikon'],
  [/\bsilikón\b/g, 'silikon'],
  [/\bAkrylový tmel\b/g, 'Akrylový tmel'],
  [/\bMontážne lepidlo\b/g, 'Montážní lepidlo'],
  [/\bIzolačná páska\b/g, 'Izolační páska'],
  [/\bLepiaca páska strieborná\b/g, 'Lepicí páska stříbrná'],
  [/\bLepiaca páska\b/g, 'Lepicí páska'],
  [/\bdo SDK\b/g, 'do SDK'],
  [/\bdo dreva\b/g, 'do dřeva'],
  [/\bOchranné rukavice\b/g, 'Ochranné rukavice'],
  [/\bKontaktný sprej\b/g, 'Kontaktní sprej'],
  [/\bOdmasťovač\b/g, 'Odmašťovač'],
  // Flexi
  [/\bFlexi hadica\b/g, 'Flexi hadice'],
  [/\bRohový ventil\b/g, 'Rohový ventil'],
  [/\bGuľový ventil\b/g, 'Kulový ventil'],
  [/\bguľový ventil\b/g, 'kulový ventil'],
  [/\bSpätný ventil\b/g, 'Zpětný ventil'],
  [/\bspätný ventil\b/g, 'zpětný ventil'],
  [/\bRedukčný ventil\b/g, 'Redukční ventil'],
  [/\bPoistný ventil\b/g, 'Pojistný ventil'],
  [/\bpoistný ventil\b/g, 'pojistný ventil'],
  [/\bPPR\b/g, 'PPR'],
  [/\blistovacia\b/g, 'lisovací'],
  [/\bListovacia\b/g, 'Lisovací'],
  [/\bLisovacia\b/g, 'Lisovací'],
  // ── Missing translations (audit 2026-04-05 + expansion) ──
  [/\bZáchytná vanička\b/g, 'Záchytná vanička'],
  [/\bzáchytná vanička\b/g, 'záchytná vanička'],
  [/\bZáchytný ventil\b/g, 'Záchytný ventil'],
  [/\bzáchytný ventil\b/g, 'záchytný ventil'],
  [/\bListovacia spojka\b/g, 'Lisovací spoj'],
  [/\blistovacia spojka\b/g, 'lisovací spoj'],
  [/\bLisovacia spojka\b/g, 'Lisovací spoj'],
  [/\bLisovacia prechodka\b/g, 'Lisovací přechod'],
  [/\bTermoaktuátor\b/g, 'Termoaktuátor'],
  [/\btermoaktuátor\b/g, 'termoaktuátor'],
  [/\bVyhrievací kábel\b/g, 'Topný kabel'],
  [/\bvyhrievací kábel\b/g, 'topný kabel'],
  [/\bElektrická vykurovacia rohož\b/g, 'Elektrická topná rohož'],
  [/\bvykurovacia rohož\b/g, 'topná rohož'],
  [/\bExteriérový snímač\b/g, 'Exteriérový snímač'],
  [/\bexteriérový snímač\b/g, 'exteriérový snímač'],
  [/\bplynomerná skriňa\b/g, 'plynoměrná skříň'],
  [/\bPlynomerná skriňa\b/g, 'Plynoměrná skříň'],
  [/\bplynomernej skrinke\b/g, 'plynoměrné skříni'],
  [/\bNeutralizátor kondenzátu\b/g, 'Neutralizátor kondenzátu'],
  [/\bneutralizátor kondenzátu\b/g, 'neutralizátor kondenzátu'],
  [/\bNáplň neutralizátora\b/g, 'Náplň neutralizátoru'],
  [/\bServisná sada kotla\b/g, 'Servisní sada kotle'],
  [/\bEndoskopická kamera\b/g, 'Endoskopická kamera'],
  [/\bendoskopická kamera\b/g, 'endoskopická kamera'],
  [/\bSeptikové baktérie\b/g, 'Septikové bakterie'],
  [/\bseptikové baktérie\b/g, 'septikové bakterie'],
  [/\bBiologický aktivátor\b/g, 'Biologický aktivátor'],
  [/\bWallbox nabíjacia stanica\b/g, 'Wallbox nabíjecí stanice'],
  [/\bWallbox príslušenstvo\b/g, 'Wallbox příslušenství'],
  [/\bnabíjacia stanica EV\b/g, 'nabíjecí stanice EV'],
  [/\bMerač spotreby energie\b/g, 'Měřič spotřeby energie'],
  [/\bFVE istič\b/g, 'FVE jistič'],
  [/\bFVE prúdový chránič\b/g, 'FVE proudový chránič'],
  [/\bKábel pre FVE\b/g, 'Kabel pro FVE'],
  [/\bDigitálny multimeter\b/g, 'Digitální multimetr'],
  [/\bMerač izolácie\b/g, 'Měřič izolace'],
  [/\bTepelná izolácia Cu potrubia\b/g, 'Tepelná izolace Cu potrubí'],
  [/\bIzolácia kondenzačnej hadice\b/g, 'Izolace kondenzační hadice'],
  [/\bKompresor split jednotky\b/g, 'Kompresor split jednotky'],
  [/\bRozbehovací kondenzátor split\b/g, 'Rozběhový kondenzátor split'],
  [/\bPresostat split\b/g, 'Presostat split'],
  [/\bDrenážna vaňa split\b/g, 'Drenážní vana split'],
  [/\bWiFi modul klimatizácie\b/g, 'WiFi modul klimatizace'],
  [/\bTrezorový zámok\b/g, 'Trezorový zámek'],
  [/\btrezorový zámok\b/g, 'trezorový zámek'],
  [/\bAutoklúč transponder\b/g, 'Autoklíč transponder'],
  [/\bFAB vložka bezpečnostná\b/g, 'FAB vložka bezpečnostní'],
  [/\bBezpečnostná fólia\b/g, 'Bezpečnostní fólie'],
  [/\bDverný odpor\b/g, 'Dveřní odpor'],
  [/\bMagnetický alarm\b/g, 'Magnetický alarm'],
  [/\bStrešný výlez\b/g, 'Střešní výlez'],
  [/\bstrešný výlez\b/g, 'střešní výlez'],
  [/\bOdvetrávacia hlavica\b/g, 'Větrací hlavice'],
  [/\bodvetrávacia hlavica\b/g, 'větrací hlavice'],
  [/\bStrešná lávka\b/g, 'Střešní lávka'],
  [/\bstrešná lávka\b/g, 'střešní lávka'],
  [/\bBezpečnostný strešný hák\b/g, 'Bezpečnostní střešní hák'],
  [/\bStrešný vetrák\b/g, 'Střešní větrák'],
  [/\bHrebňová vetracia páska\b/g, 'Hřebenová větrací páska'],
  [/\bMuflón strešný\b/g, 'Manžeta střešní'],
  [/\bDlažba protišmyková\b/g, 'Dlažba protiskluzová'],
  [/\bdlažba protišmyková\b/g, 'dlažba protiskluzová'],
  [/\bprotišmyková\b/g, 'protiskluzová'],
  [/\bVeľkoformátová dlažba\b/g, 'Velkoformátová dlažba'],
  [/\bveľkoformátová dlažba\b/g, 'velkoformátová dlažba'],
  [/\bMozaika\b/g, 'Mozaika'],
  [/\bmozaika\b/g, 'mozaika'],
  [/\bKamenný obklad\b/g, 'Kamenný obklad'],
  [/\bkamenný obklad\b/g, 'kamenný obklad'],
  [/\bObklad dekoratívny\b/g, 'Obklad dekorativní'],
  [/\bFlexibilné lepidlo\b/g, 'Flexibilní lepidlo'],
  [/\bPohľadový betón\b/g, 'Pohledový beton'],
  [/\bpohľadový betón\b/g, 'pohledový beton'],
  [/\bBetónová zálievka\b/g, 'Betonová zálivka'],
  [/\bSamonivelačná stierka rýchla\b/g, 'Samonivelační stěrka rychlá'],
  [/\bKontaktná stierka ETICS\b/g, 'Kontaktní stěrka ETICS'],
  [/\bVyrovnávacia malta\b/g, 'Vyrovnávací malta'],
  [/\bStudňové lano\b/g, 'Studňové lano'],
  [/\bHadica tlaková čerpacie\b/g, 'Hadice tlaková čerpací'],
  [/\bZpevňovacia sieť studne\b/g, 'Zpevňovací síť studny'],
  [/\bHDPE potrubie tlakovania\b/g, 'HDPE potrubí tlakované'],
  [/\bHDPE elektrotvarovka\b/g, 'HDPE elektrotvarovka'],
  [/\bPrechodka základom\b/g, 'Průchodka základem'],
  [/\brektifikovaná\b/g, 'rektifikovaná'],
  [/\bbez zmrašťovania\b/g, 'bez smršťování'],
  [/\bštukatúra\b/g, 'štukatúra'],
  [/\bzálievka\b/g, 'zálivka'],
  [/\bZálievka\b/g, 'Zálivka'],
  [/\bpre šikmú strechu\b/g, 'pro šikmou střechu'],
  [/\bpre rovnú strechu\b/g, 'pro rovnou střechu'],
  [/\bso sieťkou\b/g, 'se síťkou'],
  [/\bso spätnou klapkou\b/g, 'se zpětnou klapkou'],
  [/\bspätný\b/g, 'zpětný'],
  [/\bspätnú\b/g, 'zpětnou'],
  [/\bspätnou\b/g, 'zpětnou'],
  [/\bkľúčový\b/g, 'klíčový'],
  [/\bkúpeľňa\b/g, 'koupelna'],
  [/\bkúpeľni\b/g, 'koupelně'],
  [/\bvypúšťaním\b/g, 'vypouštěním'],

  [/\bmotýlik\b/g, 'motýlek'],
  [/\bvnút\.\b/g, 'vnitř.'],
  [/\bvonk\.\b/g, 'venk.'],
  [/\bs manometrom\b/g, 's manometrem'],
  [/\bflexibilná\b/g, 'flexibilní'],
  [/\bsúprava\b/g, 'souprava'],
  [/\bSúprava\b/g, 'Souprava'],
  [/\bpodomietková\b/g, 'podomítková'],
  [/\bnízka\b/g, 'nízká'],
  [/\bvysoká\b/g, 'vysoká'],
  [/\bpriame\b/g, 'přímé'],
  [/\bUzatvárací\b/g, 'Uzavírací'],
  [/\buzatvárací\b/g, 'uzavírací'],
  [/\bšróbenie\b/g, 'šroubení'],
  [/\bŠróbenie\b/g, 'Šroubení'],
  [/\bkúrenia\b/g, 'vytápění'],
  [/\bvykurovacej\b/g, 'otopné'],
  [/\bkotla\b/g, 'kotle'],
  [/\baxiálny\b/g, 'axiální'],
  [/\btekutinová\b/g, 'kapalinová'],
  [/\bprogramovateľná\b/g, 'programovatelná'],
  [/\bokruhov\b/g, 'okruhů'],
  [/\bkvapalina\b/g, 'kapalina'],
  [/\bKvapalina\b/g, 'Kapalina'],
  [/\bAnténny\b/g, 'Anténní'],
  [/\banténny\b/g, 'anténní'],
  [/\bzáložný\b/g, 'záložní'],
  [/\bZáložný\b/g, 'Záložní'],
  [/\bKondenzačná\b/g, 'Kondenzační'],
  [/\bkondenzačná\b/g, 'kondenzační'],
  [/\bvnútornej\b/g, 'vnitřní'],
  [/\bvonkajšej\b/g, 'venkovní'],
  [/\bventilátora\b/g, 'ventilátoru'],
  [/\bdvojstĺpový\b/g, 'dvousloupový'],
  [/\bneutrálny\b/g, 'neutrální'],
  [/\bKomunikačný\b/g, 'Komunikační'],
  [/\bkomunikačný\b/g, 'komunikační'],
]

/** Strip diacritics for fuzzy comparison */
export function stripDiacritics(text: string): string {
  return text.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase()
}

/**
 * Find canonical (with-diacritics) name from catalog for a user-typed name.
 * Returns the catalog version if found, otherwise returns input unchanged.
 */
export function findCanonicalName(input: string, category: string, lang?: string): string {
  const code = getCategoryCode(category)
  const rawItems = [...(MATERIAL_CATALOG[code] || []), ...UNIVERSAL_MATERIALS]
  const items = lang === 'cz' ? rawItems.map(translateItem) : rawItems
  const inputStripped = stripDiacritics(input)
  const match = items.find(i => stripDiacritics(i.name) === inputStripped)
  return match ? match.name : input
}

/**
 * Pre-compute Unicode-aware versions of SK_CZ_WORDS patterns.
 * JS \b only recognizes [a-zA-Z0-9_] as word chars, so diacritics like ľ, ý, á
 * break \b word boundaries. We convert \b → (?<!\p{L}) / (?!\p{L}) with /u flag.
 */
const SK_CZ_UNICODE: [RegExp, string][] = SK_CZ_WORDS.map(([pattern, replacement]) => {
  const src = pattern.source
    .replace(/^\\b/, '(?<!\\p{L})')
    .replace(/\\b$/, '(?!\\p{L})')
  return [new RegExp(src, 'gu'), replacement]
})

/** Translate a SK string to CZ using word replacements */
export function skToCz(text: string): string {
  let result = text
  for (const [pattern, replacement] of SK_CZ_UNICODE) {
    result = result.replace(pattern, replacement)
  }
  return result
}

/** Translate a MaterialItem to CZ */
function translateItem(item: MaterialItem): MaterialItem {
  return {
    name: skToCz(item.name),
    brands: item.brands,
    types: item.types?.map(t => skToCz(t)),
  }
}

// ═══════════════════════════════════════════════════════════════════
// CATALOG PER CATEGORY — hierarchical: name → brands + types
// ═══════════════════════════════════════════════════════════════════

const MATERIAL_CATALOG: Record<string, MaterialItem[]> = {

  // ─── 01. Plumber (Instalatér) ─────────────────────────────────
  '01': [
    // Sifóny
    { name: 'Sifón umývadlový', brands: ['Alcaplast', 'HL', 'Viega', 'Prevex'], types: ['DN32', 'DN40', 'DN50', 's prepadom', 'bez prepadu', 'chrómový', 'biely'] },
    { name: 'Sifón drezový', brands: ['Alcaplast', 'HL', 'Viega', 'Prevex'], types: ['DN50', 'jednoduchý', 'dvojitý', 's prepadom', 'priestorovo úsporný'] },
    { name: 'Sifón vaňový', brands: ['Alcaplast', 'Viega', 'Geberit'], types: ['automatický click-clack', 'lanko', 'bowden', 'DN40', 'DN50'] },
    { name: 'Sifón sprchový', brands: ['Alcaplast', 'HL', 'Viega', 'Geberit'], types: ['DN40', 'DN50', 'nízky 52mm', 'nízky 60mm', 'lineárny žľab'] },
    { name: 'Sifón podlahový', brands: ['Alcaplast', 'HL'], types: ['DN50', 'DN75', 'DN110', 'suchá zápachová uzávera', 'nerez mriežka'] },
    { name: 'Sifón práčkový', brands: ['Alcaplast', 'HL'], types: ['podomietkový', 'nástenný', 'DN40', 'DN50'] },
    { name: 'Sifón kondenzačný', types: ['DN32', 'pre kotol', 'pre klímu'] },
    // Flexi hadice
    { name: 'Flexi hadica', brands: ['Slovarm', 'Arco', 'Bugatti'], types: ['3/8" 30cm', '3/8" 40cm', '3/8" 50cm', '1/2" 30cm', '1/2" 40cm', '1/2" 50cm', '1/2" 80cm', '1/2" 100cm', '3/4" 50cm', '3/4" 80cm', '3/4" 100cm'] },
    // Ventily
    { name: 'Rohový ventil', brands: ['Slovarm', 'Arco', 'Bugatti', 'Schell'], types: ['1/2"', '1/2" s filtrom', '3/8"', '3/4"', 'kombinovaný', 'samouzatvárací'] },
    { name: 'Guľový ventil', brands: ['Bugatti', 'Arco', 'Slovarm', 'FIV'], types: ['1/2"', '3/4"', '1"', '5/4"', '6/4"', '2"', 'páka', 'motýlik', 'vnút./vnút.', 'vnút./vonk.'] },
    { name: 'Spätný ventil', brands: ['Bugatti', 'Arco', 'FIV'], types: ['1/2"', '3/4"', '1"', '5/4"', 'mosadzný', 'nerez'] },
    { name: 'Redukčný ventil tlaku', brands: ['Honeywell', 'Caleffi', 'Watts'], types: ['1/2"', '3/4"', '1"', '1-6 bar', 'nastaviteľný', 's manometrom'] },
    { name: 'Poistný ventil', types: ['3 bar', '6 bar', '8 bar', '10 bar', '1/2"', '3/4"'] },
    // PVC odpad
    { name: 'PVC rúra', types: ['DN32 0,5m', 'DN32 1m', 'DN40 0,5m', 'DN40 1m', 'DN50 0,5m', 'DN50 1m', 'DN50 2m', 'DN75 1m', 'DN75 2m', 'DN110 0,5m', 'DN110 1m', 'DN110 2m', 'DN110 3m', 'DN125 1m', 'DN160 1m'] },
    { name: 'PVC koleno 45°', types: ['DN32', 'DN40', 'DN50', 'DN75', 'DN110', 'DN125', 'DN160'] },
    { name: 'PVC koleno 90°', types: ['DN32', 'DN40', 'DN50', 'DN75', 'DN110', 'DN125', 'DN160'] },
    { name: 'PVC koleno 87°', types: ['DN50', 'DN75', 'DN110'] },
    { name: 'PVC odbočka', types: ['DN110/50', 'DN110/75', 'DN110/110', 'DN125/110', 'DN160/110', '45°', '87°'] },
    { name: 'PVC redukcia', types: ['DN40/32', 'DN50/40', 'DN75/50', 'DN110/50', 'DN110/75', 'DN125/110', 'DN160/110'] },
    { name: 'PVC zasúvka', types: ['DN32', 'DN40', 'DN50', 'DN75', 'DN110'] },
    { name: 'PVC čistiaci kus', types: ['DN50', 'DN75', 'DN110'] },
    { name: 'PVC prechod HT/KG', types: ['DN110', 'DN125', 'DN160'] },
    { name: 'PVC T-kus', types: ['DN40', 'DN50', 'DN75', 'DN110'] },
    // PPR voda
    { name: 'PPR rúra', brands: ['Wavin Ekoplastik', 'FV Plast', 'Instaplast'], types: ['16mm', '20mm', '25mm', '32mm', '40mm', '50mm', 'PN16', 'PN20', 'STABI'] },
    { name: 'PPR koleno 90°', brands: ['Wavin Ekoplastik', 'FV Plast'], types: ['16mm', '20mm', '25mm', '32mm'] },
    { name: 'PPR koleno 45°', brands: ['Wavin Ekoplastik', 'FV Plast'], types: ['20mm', '25mm', '32mm'] },
    { name: 'PPR T-kus', brands: ['Wavin Ekoplastik', 'FV Plast'], types: ['16mm', '20mm', '25mm', '32mm', 'redukovaný'] },
    { name: 'PPR spojka', brands: ['Wavin Ekoplastik', 'FV Plast'], types: ['16mm', '20mm', '25mm', '32mm'] },
    { name: 'PPR redukcia', brands: ['Wavin Ekoplastik'], types: ['25/20mm', '32/20mm', '32/25mm', '40/25mm', '40/32mm'] },
    { name: 'PPR prechodka vnútorná', brands: ['Wavin Ekoplastik'], types: ['20mm x 1/2"', '25mm x 3/4"', '32mm x 1"'] },
    { name: 'PPR prechodka vonkajšia', brands: ['Wavin Ekoplastik'], types: ['20mm x 1/2"', '25mm x 3/4"', '32mm x 1"'] },
    { name: 'PPR stenová doska', brands: ['Wavin Ekoplastik'], types: ['16mm x 1/2"', '20mm x 1/2"', '20mm x 3/4"'] },
    { name: 'PPR uzáver', brands: ['Wavin Ekoplastik'], types: ['20mm', '25mm', '32mm'] },
    // Tesnenia
    { name: 'Tesniaca pasta + konope' },
    { name: 'Teflónová páska', types: ['12mm', '19mm', 'na plyn (žltá)'] },
    { name: 'Gumové tesnenie ploché', types: ['1/2"', '3/4"', '1"', '5/4"', '6/4"'] },
    { name: 'O-krúžok', types: ['sada rôzne', '10mm', '15mm', '20mm', '25mm', '30mm'] },
    { name: 'Objímka opravná', brands: ['GEBO'], types: ['DN15', 'DN20', 'DN25', 'DN32', 'DN40', 'DN50'] },
    { name: 'Rýchlospojka GEBO', brands: ['GEBO'], types: ['1/2"', '3/4"', '1"', '5/4"', 'priama', 'T-kus', 'koleno'] },
    { name: 'Manžeta gumová', types: ['DN40', 'DN50', 'DN75', 'DN110', 'DN125'] },
    // WC
    { name: 'WC sedátko', brands: ['Cersanit', 'Jika', 'Roca', 'Ideal Standard', 'Villeroy & Boch'], types: ['štandardné', 'pomalé sklápanie (softclose)', 'antibakteriálne', 'duroplast', 'termoplast'] },
    { name: 'WC napúšťací ventil', brands: ['Alcaplast', 'Geberit', 'OLI'], types: ['bočný prívod', 'spodný prívod', '3/8"', '1/2"'] },
    { name: 'WC vypúšťací ventil', brands: ['Alcaplast', 'Geberit', 'OLI'], types: ['jednoduché splachovanie', 'dvojité splachovanie (3/6L)', 'stop tlačidlo'] },
    { name: 'WC mechanizmus komplet', brands: ['Alcaplast', 'Geberit', 'OLI'], types: ['bočný prívod', 'spodný prívod', 'dual flush'] },
    { name: 'WC tlačidlo ovládacie', brands: ['Alcaplast', 'Geberit', 'Viega'], types: ['biele', 'chrómové', 'matné', 'M270', 'M370', 'Sigma 20', 'Sigma 30'] },
    { name: 'WC tesniaci krúžok' },
    { name: 'WC manžeta', types: ['priama DN110', 'excentrická DN110', 'odsadená 40mm', 'odsadená 90mm', 'flexibilná'] },
    { name: 'WC pripojovacia súprava' },
    { name: 'WC nádržka', brands: ['Cersanit', 'Jika', 'Geberit'], types: ['nástennná', 'podomietková', 'rohová'] },
    { name: 'WC misa', brands: ['Cersanit', 'Jika', 'Roca', 'Ideal Standard', 'Villeroy & Boch', 'Duravit'], types: ['závesná', 'stojaca', 'kombi', 'rimless', 'hĺbkové splachovanie'] },
    { name: 'WC inštalačný modul', brands: ['Geberit', 'Alcaplast', 'Viega', 'Grohe'], types: ['Duofix', 'Sádromodul', 'štandard', 'nízky'] },
    // Batérie
    { name: 'Batéria umývadlová', brands: ['Grohe', 'Hansgrohe', 'Hansa', 'Ideal Standard', 'Roca', 'RAVAK', 'Cersanit'], types: ['páková', 'stojančeková', 'vysoká', 'nízka', 'senzorová', 'podomietková'] },
    { name: 'Batéria drezová', brands: ['Grohe', 'Hansgrohe', 'Hansa', 'Blanco'], types: ['páková', 's výsuvnou sprškou', 'vysoký oblúk', 'nízky oblúk', 'filtrovaná voda 2in1'] },
    { name: 'Batéria sprchová', brands: ['Grohe', 'Hansgrohe', 'Hansa', 'Ideal Standard', 'RAVAK'], types: ['páková', 'termostatická', 'podomietková', 'nástenná'] },
    { name: 'Batéria vaňová', brands: ['Grohe', 'Hansgrohe', 'Hansa', 'RAVAK'], types: ['páková', 'termostatická', 'podomietková', 'voľne stojaca'] },
    { name: 'Batéria bidetová', brands: ['Grohe', 'Hansgrohe', 'Ideal Standard'] },
    { name: 'Kartuša', types: ['35mm', '40mm', '46mm', 'keramická', 'termostatická'] },
    { name: 'Perlator', types: ['M22 vnútorný', 'M24 vonkajší', 'úsporný', 'štandardný'] },
    // Sprchy
    { name: 'Sprchová hadica', brands: ['Grohe', 'Hansgrohe', 'RAVAK'], types: ['150cm', '160cm', '175cm', '200cm', 'chrómová', 'matná'] },
    { name: 'Sprchová hlavica ručná', brands: ['Grohe', 'Hansgrohe', 'RAVAK'], types: ['1-prúd', '3-prúdy', '5-prúdov', 'úsporná', 'dažďová'] },
    { name: 'Sprchová hlavica hlavová', brands: ['Grohe', 'Hansgrohe'], types: ['200mm', '250mm', '300mm', 'okrúhla', 'štvorcová'] },
    { name: 'Sprchová tyč', brands: ['Grohe', 'Hansgrohe', 'RAVAK'], types: ['60cm', '70cm', '90cm', 's mydelničkou'] },
    // Bojlery
    { name: 'Bojler elektrický', brands: ['Dražice', 'Ariston', 'Tatramat', 'Stiebel Eltron', 'Gorenje'], types: ['30L', '50L', '80L', '100L', '120L', '150L', '200L', 'zvislý', 'vodorovný', 'kombinovaný'] },
    { name: 'Prietokový ohrievač', brands: ['Clage', 'Stiebel Eltron', 'AEG'], types: ['3,5kW', '5,5kW', '7,5kW', '11kW', '18kW', '21kW', '24kW'] },
    { name: 'Zásobníkový ohrievač', brands: ['Ariston', 'Clage', 'Stiebel Eltron'], types: ['5L', '10L', '15L', 'pod drez', 'nad drez'] },
    // Čerpadlá
    { name: 'Čerpadlo kalové', brands: ['Grundfos', 'Wilo', 'DAB'], types: ['ponorné', 'pre čistú vodu', 'pre špinavú vodu'] },
    { name: 'Čerpadlo cirkulačné', brands: ['Grundfos', 'Wilo', 'DAB'], types: ['pre TUV', 'UP 15-14', 'UP 15-20'] },
    // Meranie & filtre
    { name: 'Manometer', types: ['0-6 bar', '0-10 bar', '0-16 bar', '1/4"', '1/2"'] },
    { name: 'Vodomer bytový', types: ['1/2"', '3/4"', 'studená voda', 'teplá voda', 'suchobežný', 'mokrobežný'] },
    { name: 'Filter mechanický', brands: ['Honeywell', 'BWT', 'Caleffi'], types: ['1/2"', '3/4"', '1"', 'samočistiaci', 'výmenný'] },
    // Revízia
    { name: 'Revízne dvierka', types: ['150x150mm', '200x200mm', '200x300mm', '300x300mm', '300x400mm', '400x400mm', '500x500mm', '600x600mm', 'plastové', 'nerez', 'pod obklad'] },
    // Lisované spoje Cu/multivrstevné
    { name: 'Lisovacia spojka Cu', brands: ['Viega Profi-Press', 'Geberit Mapress', 'Sanha'], types: ['15mm', '18mm', '22mm', '28mm', '35mm', '42mm'] },
    { name: 'Lisovacie koleno Cu 90°', brands: ['Viega Profi-Press', 'Geberit Mapress'], types: ['15mm', '18mm', '22mm', '28mm'] },
    { name: 'Lisovací T-kus Cu', brands: ['Viega Profi-Press', 'Geberit Mapress'], types: ['15mm', '18mm', '22mm', '28mm'] },
    { name: 'Lisovacia prechodka Cu', brands: ['Viega Profi-Press', 'Geberit Mapress'], types: ['15mm x 1/2"', '18mm x 3/4"', '22mm x 3/4"', '22mm x 1"', '28mm x 1"'] },
    // Cu rúry (inštalatérske)
    { name: 'Cu rúra', types: ['10mm (m)', '12mm (m)', '15mm (m)', '18mm (m)', '22mm (m)', '28mm (m)', 'tvrdá', 'mäkká v kotúči'] },
    // Záchytná vanička
    { name: 'Záchytná vanička', types: ['pod bojler 80x80cm', 'pod bojler 100x100cm', 'pod práčku', 'pod umývadlo', 'plastová', 'nerezová'] },
    // Flexibilné napájanie WC
    { name: 'WC flexibilné napájanie', types: ['3/8" 30cm', '3/8" 40cm', '3/8" 50cm', 'pochrómoviné', 'plastové'] },
    // Bojlerové tesnenia
    { name: 'Tesnenie bojlera', types: ['prírubové 6/4"', 'prírubové 5/4"', 'O-krúžok vstup/výstup', 'sada tesnení'] },
    // Záchytný ventil
    { name: 'Záchytný ventil', brands: ['Honeywell', 'Caleffi'], types: ['3/4"', '1"', 'spätný s vypúšťaním'] },
  ],

  // ─── 02. Heating (Kúrenár) ────────────────────────────────────
  '02': [
    { name: 'Radiátor panelový', brands: ['Korado', 'Purmo', 'Kermi', 'Buderus', 'Brugman'], types: ['300x600', '300x800', '300x1000', '400x600', '400x800', '400x1000', '500x600', '500x800', '500x1000', '500x1200', '500x1400', '600x600', '600x800', '600x1000', '600x1200', '600x1400', '600x1600', '600x1800', '600x2000', 'typ 10', 'typ 11', 'typ 21', 'typ 22', 'typ 33'] },
    { name: 'Radiátor kúpeľňový rebríkový', brands: ['Korado', 'Purmo', 'PMH'], types: ['450x700', '450x900', '450x1200', '600x900', '600x1200', '600x1500', '600x1800', 'rovný', 'oblý', 'biely', 'chrómový'] },
    { name: 'Radiátor článkový', brands: ['Kalor', 'Viadrus', 'Global'], types: ['hliníkový', 'liatinový', 'bimetalový', '500mm', '600mm', '800mm'] },
    { name: 'Radiátorový ventil termostatický', brands: ['Danfoss', 'Heimeier', 'Honeywell', 'Herz', 'Caleffi'], types: ['priamy 1/2"', 'rohový 1/2"', 'axiálny 1/2"', 'priamy 3/4"', 'rohový 3/4"', 'M30x1,5'] },
    { name: 'Termostatická hlavica', brands: ['Danfoss', 'Heimeier', 'Honeywell', 'Herz', 'Caleffi'], types: ['štandardná', 'programovateľná', 'WiFi smart', 'M30x1,5', 'RA-N', 'tekutinová', 'vosková'] },
    { name: 'Uzatvárací šróbenie', types: ['priame 1/2"', 'rohové 1/2"', 'priame 3/4"', 'rohové 3/4"'] },
    { name: 'H-kus radiátorový', types: ['priamy 1/2"', 'rohový 1/2"', 'priamy vnút./vonk.'] },
    { name: 'Odvzdušňovací ventil', types: ['automatický 1/2"', 'automatický 3/8"', 'ručný (Majevského)', 'kľúčik'] },
    { name: 'Radiátorová zátka', types: ['1"', '5/4"', 'ľavá', 'pravá'] },
    { name: 'Radiátorová redukcia', types: ['1" / 1/2"', '5/4" / 1/2"', '5/4" / 3/4"'] },
    { name: 'Konzola radiátorová', types: ['300mm', '400mm', '500mm', '600mm', 'staviteľná'] },
    // Cu potrubia
    { name: 'Cu rúra', types: ['10mm', '12mm', '15mm', '18mm', '22mm', '28mm', '35mm', '42mm', '54mm'] },
    { name: 'Cu koleno 90°', types: ['12mm', '15mm', '18mm', '22mm', '28mm'] },
    { name: 'Cu koleno 45°', types: ['15mm', '18mm', '22mm', '28mm'] },
    { name: 'Cu T-kus', types: ['12mm', '15mm', '18mm', '22mm', '28mm', 'redukovaný'] },
    { name: 'Cu spojka', types: ['12mm', '15mm', '18mm', '22mm', '28mm'] },
    { name: 'Cu redukcia', types: ['18/15mm', '22/15mm', '22/18mm', '28/22mm', '28/18mm'] },
    { name: 'Cu prechodka', types: ['15mm x 1/2" vnút.', '15mm x 1/2" vonk.', '18mm x 3/4" vonk.', '22mm x 3/4" vonk.', '22mm x 1" vonk.', '28mm x 1" vonk.'] },
    { name: 'Lisovacia spojka', brands: ['Viega', 'Geberit Mapress', 'Sanha'], types: ['15mm', '18mm', '22mm', '28mm'] },
    { name: 'Lisovacie koleno', brands: ['Viega', 'Geberit Mapress'], types: ['15mm', '18mm', '22mm', '28mm'] },
    { name: 'Spájka mäkká', types: ['Sn97Cu3', 'Sn97Ag3', 'bezólová'] },
    { name: 'Tavidlo', types: ['na mäkké spájkovanie', 'na tvrdé spájkovanie'] },
    // Izolácie
    { name: 'Izolácia potrubia', brands: ['Armacell', 'K-Flex', 'Rockwool'], types: ['12mm', '15mm', '18mm', '22mm', '28mm', '35mm', 'hr. 9mm', 'hr. 13mm', 'hr. 19mm', 'hr. 25mm'] },
    // Expanzné nádoby
    { name: 'Expanzná nádoba', brands: ['Flamco', 'Varem', 'Zilmet', 'Reflex'], types: ['6L', '8L', '12L', '18L', '24L', '35L', '50L', 'závesná', 'stojaca'] },
    { name: 'Membrána do expanznej nádoby', types: ['8L', '12L', '18L', '24L', '35L'] },
    // Čerpadlá
    { name: 'Obehové čerpadlo', brands: ['Grundfos', 'Wilo', 'DAB'], types: ['25-40', '25-60', '25-80', '32-60', 'Alpha2', 'Yonos PICO'] },
    // Bezpečnosť
    { name: 'Bezpečnostný ventil', types: ['1,5 bar', '2,5 bar', '3 bar', '4 bar', '6 bar', '1/2"', '3/4"'] },
    { name: 'Bezpečnostná skupina', types: ['do 200kW', 'do 50kW'] },
    { name: 'Plniaci ventil' },
    { name: 'Vypúšťací kohút', types: ['1/2"', '3/4"'] },
    // Podlahové kúrenie
    { name: 'Rúrka podlahového kúrenia', brands: ['Rehau', 'Uponor', 'Wavin'], types: ['PEX 16mm', 'PEX 17mm', 'PEX 20mm', 'PERT 16mm', 'PERT 20mm'] },
    { name: 'Rozdeľovač podlahového kúrenia', brands: ['Rehau', 'Uponor', 'Giacomini', 'Caleffi'], types: ['2 okruhy', '3 okruhy', '4 okruhy', '5 okruhov', '6 okruhov', '7 okruhov', '8 okruhov', '9 okruhov', '10 okruhov', '12 okruhov'] },
    { name: 'Servopohon', brands: ['Honeywell', 'Caleffi', 'Möhlenhoff'], types: ['230V', '24V', 'M30x1,5', 'NC (normálne zatvorený)', 'NO (normálne otvorený)'] },
    { name: 'Priestorový termostat', brands: ['Honeywell', 'Danfoss', 'Tado', 'Netatmo'], types: ['digitálny', 'programovateľný', 'WiFi smart', 'bezdrôtový'] },
    // Rôzne
    { name: 'Filter vykurovacej vody', brands: ['Caleffi', 'Honeywell'] },
    { name: 'Magnetický filter', brands: ['Adey', 'Caleffi', 'Flamco'], types: ['1/2"', '3/4"', '1"'] },
    { name: 'Nemrznúca zmes', types: ['5L', '10L', '20L', 'propylénglykol', 'etylénglykol'] },
    { name: 'Inhibítor korózie', brands: ['Adey', 'Sentinel'] },
    // Podlahové kúrenie — elektrické
    { name: 'Termoaktuátor podlahového kúrenia', brands: ['Honeywell', 'Caleffi', 'Möhlenhoff', 'Siemens'], types: ['230V M30x1,5', '24V M30x1,5', 'NC (normálne zatvorený)', 'NO (normálne otvorený)'] },
    { name: 'Vyhrievací kábel', brands: ['Devi', 'Fenix', 'Raychem'], types: ['10W/m', '17W/m', '20W/m', '25W/m', 'jednožilový', 'dvojžilový', 'samoregulačný'] },
    { name: 'Elektrická vykurovacia rohož', brands: ['Devi', 'Fenix', 'Ecofloor'], types: ['100W/m²', '150W/m²', '200W/m²', '0,5m²', '1m²', '1,5m²', '2m²', '3m²', '4m²', '5m²'] },
    { name: 'Termostat pre elektrické vykurovanie', brands: ['Danfoss', 'Devi', 'Fenix', 'Salus'], types: ['digitálny', 'dotykový', 'WiFi smart', 'so snímačom podlahy'] },
    // Exteriérový snímač
    { name: 'Exteriérový snímač teploty', brands: ['Honeywell', 'Vaillant', 'Buderus'], types: ['NTC', 'PT1000', 'pre kotol', 'pre tepelné čerpadlo'] },
  ],

  // ─── 03. Gasman (Plynár) ──────────────────────────────────────
  '03': [
    { name: 'Plynová hadica', types: ['1/2" 75cm', '1/2" 100cm', '1/2" 125cm', '1/2" 150cm', '1/2" 200cm', '3/4" 100cm', '3/4" 150cm'] },
    { name: 'Plynový guľový ventil', brands: ['Bugatti', 'Arco', 'FIV'], types: ['1/2"', '3/4"', '1"', '5/4"', 'páka', 'motýlik'] },
    { name: 'Plynový bezpečnostný ventil' },
    { name: 'Regulátor tlaku plynu', types: ['0-50 mbar', 'nastaviteľný', 'pre PB bombu'] },
    { name: 'Tesnenie plynové', brands: ['Loctite'], types: ['Loctite 577', 'ploché 1/2"', 'ploché 3/4"', 'ploché 1"', 'teflónová páska žltá'] },
    { name: 'Termočlánok', types: ['univerzálny', 'pre sporák', 'pre kotol', '30cm', '60cm', '90cm', '120cm'] },
    { name: 'Plynová tryska', types: ['zemný plyn', 'PB', 'pre sporák', 'pre kotol'] },
    { name: 'Zapaľovač sporáka', types: ['piezo', 'elektrický', 'univerzálny'] },
    { name: 'Ovládací kohút sporáka' },
    { name: 'Horák sporáka', types: ['malý', 'stredný', 'veľký', 'pomocný'] },
    { name: 'Plynová rúra oceľová', types: ['1/2" 1m', '1/2" 2m', '3/4" 1m', '3/4" 2m'] },
    { name: 'Plynové koleno 90°', types: ['1/2"', '3/4"', '1"'] },
    { name: 'Plynový T-kus', types: ['1/2"', '3/4"', '1"'] },
    { name: 'Detektor úniku plynu', brands: ['Honeywell', 'Bosch'] },
    { name: 'Detektor CO', brands: ['Honeywell', 'Kidde', 'FireAngel'] },
    { name: 'Elektromagnetický ventil plynový', types: ['1/2"', '3/4"', '1"', '230V', '24V'] },
    // Plynové potrubie a fittingy
    { name: 'Plynová flexi hadica CSST', brands: ['TracPipe', 'OmegaFlex'], types: ['DN15 (m)', 'DN20 (m)', 'DN25 (m)', 's koncovkami'] },
    { name: 'Plynový uzáver pred meradlom', types: ['1"', '5/4"', '6/4"', 'guľový', 'membránový'] },
    { name: 'Plynomerná skriňa', types: ['pre 1 merač', 'pre 2 meradlá', 'murovaná', 'oceľová', 'plastová'] },
    { name: 'Plynová rúra čierna', types: ['DN15 1/2" (m)', 'DN20 3/4" (m)', 'DN25 1" (m)', 'DN32 5/4" (m)'] },
    { name: 'Plynové koleno 90° čierne', types: ['1/2"', '3/4"', '1"', '5/4"'] },
    { name: 'Plynový T-kus čierny', types: ['1/2"', '3/4"', '1"', '5/4"'] },
    { name: 'Plynová redukcia', types: ['3/4" x 1/2"', '1" x 3/4"', '5/4" x 1"'] },
  ],

  // ─── 04. Gas boiler (Plynový kotol) ───────────────────────────
  '04': [
    { name: 'Zapaľovacia elektróda', brands: ['Vaillant', 'Junkers/Bosch', 'Protherm', 'Buderus', 'Viessmann', 'Baxi', 'Ariston', 'Wolf'] },
    { name: 'Ionizačná elektróda', brands: ['Vaillant', 'Junkers/Bosch', 'Protherm', 'Buderus', 'Viessmann', 'Baxi', 'Ariston'] },
    { name: 'Zapaľovacia jednotka / trafo', brands: ['Vaillant', 'Junkers/Bosch', 'Protherm'] },
    { name: 'Plynová armatúra', brands: ['Honeywell', 'SIT', 'Vaillant', 'Junkers/Bosch'] },
    { name: 'Výmenník tepla primárny', brands: ['Vaillant', 'Junkers/Bosch', 'Protherm', 'Buderus', 'Viessmann', 'Baxi'] },
    { name: 'Výmenník tepla sekundárny (doskový)', brands: ['Vaillant', 'Junkers/Bosch', 'Protherm', 'Zilmet', 'SWEP'] },
    { name: 'Trojcestný ventil', brands: ['Honeywell', 'Vaillant', 'Junkers/Bosch', 'Protherm'], types: ['komplet', 'len motor', 'len telo'] },
    { name: 'Obehové čerpadlo kotla', brands: ['Grundfos', 'Wilo', 'Vaillant', 'Junkers/Bosch', 'Protherm'] },
    { name: 'Expanzná nádoba kotla', types: ['6L', '8L', '10L', '12L'] },
    { name: 'Snímač teploty NTC', brands: ['Vaillant', 'Junkers/Bosch', 'Protherm'], types: ['výstup', 'spiatočka', 'TUV', 'zásobník'] },
    { name: 'Snímač tlaku vody', brands: ['Vaillant', 'Junkers/Bosch', 'Protherm'] },
    { name: 'Prietokový snímač', brands: ['Vaillant', 'Junkers/Bosch', 'Protherm'] },
    { name: 'Presostat', types: ['vzduchu (Venturi)', 'vody (hydraulický)', 'dymu'] },
    { name: 'Riadiaca doska', brands: ['Vaillant', 'Junkers/Bosch', 'Protherm', 'Buderus', 'Viessmann', 'Baxi'] },
    { name: 'Displej / ovládací panel', brands: ['Vaillant', 'Junkers/Bosch', 'Protherm'] },
    { name: 'Ventilátor (turbína)', brands: ['Vaillant', 'Junkers/Bosch', 'Protherm', 'Buderus', 'Viessmann', 'Baxi', 'EBM-Papst'] },
    { name: 'Kondenzačný sifón', types: ['DN32', 'pre kondenzačný kotol'] },
    { name: 'Dymovod', types: ['60/100mm 0,5m', '60/100mm 1m', '60/100mm 2m', '80/125mm 0,5m', '80/125mm 1m', 'koleno 90°', 'koleno 45°', 'koncovka fasádna', 'koncovka strešná', 'T-kus revízny'] },
    { name: 'Bezpečnostný ventil', types: ['3 bar', '1/2"', '3/4"'] },
    { name: 'Tesnenie výmenníka', brands: ['Vaillant', 'Junkers/Bosch', 'Protherm'], types: ['sada'] },
    { name: 'O-krúžky kotla', types: ['sada'] },
    { name: 'Filter kotlovej vody' },
    { name: 'Priestorový termostat', brands: ['Honeywell', 'Vaillant', 'Junkers/Bosch', 'Tado', 'Netatmo'], types: ['digitálny', 'programovateľný', 'WiFi', 'OpenTherm'] },
    // Kondenzátny systém
    { name: 'Neutralizátor kondenzátu', brands: ['Caleffi', 'Reflex', 'Grundfos'], types: ['pre výkon do 35kW', 'pre výkon do 70kW', 'pre výkon do 150kW', 'náplň (granulát)'] },
    { name: 'Náplň neutralizátora kondenzátu', types: ['granulát 1kg', 'granulát 2kg', 'granulát 5kg'] },
    { name: 'Servisná sada kotla', brands: ['Vaillant', 'Junkers/Bosch', 'Protherm', 'Buderus'], types: ['filtre + O-krúžky', 'elektródy + tesnenia', 'kompletná ročná servisná'] },
  ],

  // ─── 05. Electric boiler (Elektrický bojler) ──────────────────
  '05': [
    { name: 'Vyhrievacie teleso', types: ['1000W', '1200W', '1500W', '2000W', '2500W', '3000W', 'keramické', 'suchý ohrev', 'ponorné', 'prírubové'] },
    { name: 'Termostat bojlera', types: ['tyčový', 'kapilárkový', 'bezpečnostný STB', 'elektronický', 'kombinovaný'] },
    { name: 'Anódová tyč', brands: ['Dražice', 'Tatramat', 'Ariston'], types: ['Mg 22x500mm', 'Mg 22x700mm', 'Mg 26x500mm', 'Mg 33x500mm', 'titanová elektronická'] },
    { name: 'Bezpečnostný ventil', types: ['6 bar', '8 bar', '10 bar'] },
    { name: 'Bezpečnostná skupina bojlera', brands: ['Honeywell', 'Caleffi', 'Flamco'] },
    { name: 'Tesnenie príruby bojlera', brands: ['Dražice', 'Tatramat', 'Ariston'] },
    { name: 'Bojler elektrický', brands: ['Dražice', 'Tatramat', 'Ariston', 'Gorenje', 'Stiebel Eltron', 'AEG'], types: ['30L', '50L', '80L', '100L', '120L', '150L', '200L', 'zvislý', 'vodorovný'] },
    { name: 'Prietokový ohrievač', brands: ['Clage', 'Stiebel Eltron', 'AEG', 'DAFI'], types: ['3,5kW', '5,5kW', '7,5kW', '11kW', '18kW', '21kW', '24kW', 'jednofázový', 'trojfázový'] },
  ],

  // ─── 06-07: Thermal pumps & Solar — kept simple (low frequency) ─
  '06': [
    { name: 'Kompresor tepelného čerpadla', brands: ['Mitsubishi', 'Daikin', 'Panasonic', 'Toshiba', 'Copeland'] },
    { name: 'Chladivo', types: ['R410A (1kg)', 'R32 (1kg)', 'R134a (1kg)', 'R290 (1kg)'] },
    { name: 'Expanzný ventil', brands: ['Danfoss'] },
    { name: 'Štvorcestný ventil' },
    { name: 'Snímač teploty', types: ['vonkajší', 'výstup', 'spiatočka', 'TUV', 'NTC', 'PT1000'] },
    { name: 'Presostat', types: ['vysoký tlak', 'nízky tlak'] },
    { name: 'Riadiaca doska TČ', brands: ['Mitsubishi', 'Daikin', 'Panasonic', 'Viessmann'] },
    { name: 'Ventilátor vonkajšej jednotky', brands: ['Mitsubishi', 'Daikin'] },
    { name: 'Obehové čerpadlo', brands: ['Grundfos', 'Wilo'] },
    { name: 'Elektropatróna záložná', types: ['3kW', '6kW', '9kW'] },
    { name: 'Akumulačná nádoba', types: ['100L', '200L', '300L', '500L'] },
    { name: 'Nemrznúca zmes', types: ['10L', '20L'] },
  ],
  '07': [
    { name: 'Solárny panel', types: ['termický plochý', 'termický vákuový', 'fotovoltaický mono', 'fotovoltaický poly'] },
    { name: 'Solárny regulátor', brands: ['Resol', 'Steca'] },
    { name: 'Solárne čerpadlo', brands: ['Grundfos', 'Wilo'] },
    { name: 'Solárna kvapalina', types: ['10L', '20L'] },
    { name: 'Expanzná nádoba solárna', types: ['12L', '18L', '24L'] },
    { name: 'Invertor', brands: ['Fronius', 'SolarEdge', 'Huawei', 'GoodWe', 'SMA'], types: ['3kW', '5kW', '6kW', '8kW', '10kW', 'hybridný'] },
    { name: 'Batériový systém', brands: ['BYD', 'Huawei', 'Pylontech', 'Tesla'], types: ['5kWh', '10kWh', '15kWh'] },
    { name: 'Optimizér', brands: ['SolarEdge', 'Tigo'] },
    { name: 'Montážna konštrukcia', types: ['šikmá strecha', 'rovná strecha', 'fasáda', 'zem'] },
  ],

  // ─── 08. Unblocking (Odpájanie) ───────────────────────────────
  '08': [
    { name: 'Čistiaci kábel', types: ['6mm x 5m', '8mm x 7,5m', '8mm x 10m', '10mm x 10m', '12mm x 15m', '16mm x 15m', '16mm x 20m'] },
    { name: 'Čistiaca hlavica', types: ['šípová', 'reťazová', 'koreňová', 'guľová', 'univerzálna'] },
    { name: 'Chemický čistič odpadov', brands: ['Mr. Muscle', 'Bref', 'HG', 'Mellerud'], types: ['gél', 'granulát', 'tekutý'] },
    { name: 'Enzymatický čistič odpadov' },
    { name: 'Zvon na odpady', types: ['malý', 'veľký', 'gumový'] },
    { name: 'PVC zasúvka', types: ['DN32', 'DN40', 'DN50', 'DN75', 'DN110'] },
    { name: 'PVC čistiaci kus', types: ['DN50', 'DN75', 'DN110'] },
    { name: 'Sifón (výmena)', types: ['umývadlový', 'drezový', 'sprchový', 'vaňový'] },
    { name: 'Revízne dvierka', types: ['200x200mm', '300x300mm', '400x400mm'] },
    { name: 'Gumové tesnenie', types: ['DN40', 'DN50', 'DN110'] },
    // Diagnostika a biologické čistenie
    { name: 'Endoskopická kamera', types: ['20m', '30m', 'push-rod', 'samohybná', 'záznam na SD kartu'] },
    { name: 'Septikové baktérie', brands: ['Duoflow', 'Bio-Clean', 'Biopron'], types: ['prášok 1kg', 'tabletky (50ks)', 'tekutý 1L'] },
    { name: 'Biologický aktivátor odpadu', types: ['500ml', '1L', 'mesačná dávka'] },
  ],
  '09': [
    { name: 'Čistiaci kábel', types: ['16mm x 25m', '22mm x 30m', '25mm x 30m', '32mm x 30m', '32mm x 45m'] },
    { name: 'Vysokotlaková tryska', types: ['priama', 'rotačná', 'koreňová', 'reťazová'] },
    { name: 'Vysokotlaková hadica', types: ['1/4" 30m', '1/4" 60m', '3/8" 30m', '3/8" 60m'] },
    { name: 'Frézovacie hlavice', types: ['reťazová', 'koreňová', 'škrabacia'] },
    { name: 'PVC rúra', types: ['DN110 1m', 'DN110 2m', 'DN125 1m', 'DN160 1m', 'DN200 1m'] },
    { name: 'PVC koleno', types: ['DN110', 'DN125', 'DN160', 'DN200', '45°', '90°'] },
    { name: 'PVC odbočka', types: ['DN110', 'DN125', 'DN160'] },
    { name: 'Revízna šachta', types: ['DN315', 'DN400', 'DN600', 'plastová', 'betónová'] },
    { name: 'Poklop', types: ['plastový', 'liatinový', 'A15', 'B125'] },
    // Diagnostika
    { name: 'Endoskopická kamera', types: ['40m kábel', '60m kábel', '80m kábel', 'so záznamom', 'samohybná'] },
    { name: 'Čistiaci prípravok biologický', types: ['septikové baktérie 1kg', 'septikové baktérie 5kg'] },
  ],

  // ─── 10. Electrician ──────────────────────────────────────────
  '10': [
    { name: 'Istič 1P', brands: ['OEZ', 'Eaton', 'ABB', 'Schneider', 'Hager', 'Legrand'], types: ['6A B', '10A B', '13A B', '16A B', '20A B', '25A B', '32A B', '40A B', '6A C', '10A C', '16A C', '20A C', '25A C', '32A C'] },
    { name: 'Istič 3P', brands: ['OEZ', 'Eaton', 'ABB', 'Schneider', 'Hager', 'Legrand'], types: ['10A B', '16A B', '20A B', '25A B', '32A B', '40A B', '16A C', '20A C', '25A C', '32A C', '40A C', '50A C', '63A C'] },
    { name: 'Prúdový chránič', brands: ['OEZ', 'Eaton', 'ABB', 'Schneider', 'Hager', 'Legrand'], types: ['25A/30mA 2P', '40A/30mA 2P', '63A/30mA 2P', '25A/30mA 4P', '40A/30mA 4P', '63A/30mA 4P', '40A/100mA 4P', '63A/300mA 4P', 'typ A', 'typ AC', 'typ B'] },
    { name: 'Prúdový chránič s istením', brands: ['OEZ', 'Eaton', 'ABB', 'Schneider'], types: ['10A/30mA B', '16A/30mA B', '20A/30mA B', '25A/30mA B', '16A/30mA C', '20A/30mA C'] },
    { name: 'Prepäťová ochrana', brands: ['OEZ', 'Eaton', 'ABB', 'Dehn', 'Saltek'], types: ['T1 (B)', 'T2 (C) 1P', 'T2 (C) 3P+N', 'T1+T2 kombinovaná', 'T3 (D)'] },
    { name: 'Zásuvka 230V', brands: ['ABB', 'Legrand', 'Schneider', 'Hager', 'Obzor'], types: ['jednoduchá', 'dvojitá', 's USB', 's prepäťovou ochranou', 'rámček', 'IP20', 'IP44', 'biela', 'krémová', 'antracit'] },
    { name: 'Zásuvka silová', types: ['16A 3P (230V)', '16A 5P (400V)', '32A 5P (400V)', '63A 5P (400V)'] },
    { name: 'Vypínač', brands: ['ABB', 'Legrand', 'Schneider', 'Hager', 'Obzor'], types: ['č.1 jednopólový', 'č.5 sériový (dvojitý)', 'č.6 striedavý (schodiskový)', 'č.6+6 dvojitý striedavý', 'č.7 krížový', 'tlačidlo (zvonček)', 'stmievač', 'biely', 'krémový', 'antracit'] },
    { name: 'Rámček', brands: ['ABB', 'Legrand', 'Schneider'], types: ['1-násobný', '2-násobný', '3-násobný', '4-násobný', '5-násobný', 'biely', 'krémový', 'antracit'] },
    { name: 'Kábel CYKY', types: ['3x1,5mm²', '3x2,5mm²', '4x1,5mm²', '5x1,5mm²', '5x2,5mm²', '5x4mm²', '5x6mm²', '5x10mm²', '5x16mm²'] },
    { name: 'Kábel CYKYLo (plochý)', types: ['3x1,5mm²', '3x2,5mm²'] },
    { name: 'Kábel H07RN-F (gumový)', types: ['3x1,5mm²', '3x2,5mm²', '5x2,5mm²', '5x4mm²'] },
    { name: 'Vodič CY (zeleno-žltý)', types: ['4mm²', '6mm²', '10mm²', '16mm²', '25mm²'] },
    { name: 'Elektroinštalačná rúrka', types: ['16mm', '20mm', '25mm', '32mm', '40mm', 'tuhá', 'ohybná'] },
    { name: 'Chránička ohybná', types: ['16mm', '20mm', '25mm', '32mm'] },
    { name: 'Krabica prístrojová', types: ['KP68 (štandardná)', 'KP68/2 (hĺbková)', 'dvojitá', 'do SDK', 'do betónu'] },
    { name: 'Krabica odbočná', types: ['štvorcová', 'okrúhla', 'IP20', 'IP44', 'IP55'] },
    { name: 'Rozvádzač bytový', brands: ['OEZ', 'Eaton', 'ABB', 'Schneider', 'Hager'], types: ['1-rad 12M', '2-rady 24M', '3-rady 36M', '4-rady 48M', 'pod omietku', 'na omietku', 'IP30', 'IP65'] },
    { name: 'WAGO svorka', brands: ['WAGO'], types: ['2x (221-412)', '3x (221-413)', '5x (221-415)', '2x s pákou', '3x s pákou', '5x s pákou'] },
    { name: 'LED žiarovka', brands: ['Philips', 'Osram', 'Emos', 'Tungsram'], types: ['E27 8W', 'E27 10W', 'E27 13W', 'E27 15W', 'E14 5W', 'E14 7W', 'GU10 5W', 'GU10 7W', 'G9 3W', 'G9 5W', 'teplá biela 2700K', 'neutrálna 4000K', 'stmievateľná'] },
    { name: 'LED trubica T8', brands: ['Philips', 'Osram', 'Emos'], types: ['60cm 8W', '120cm 18W', '150cm 22W', 'teplá biela', 'neutrálna'] },
    { name: 'LED panel', types: ['30x30 18W', '60x60 36W', '60x60 40W', '120x30 36W', 'zapustený', 'prisadený'] },
    { name: 'LED reflektor', brands: ['Philips', 'Emos'], types: ['10W', '20W', '30W', '50W', '100W', 'so senzorom', 'bez senzora'] },
    { name: 'LED bodovka podhľadová', types: ['okrúhla', 'štvorcová', 'pevná', 'výklopná', 'biela', 'chrómová', 'nikel'] },
    { name: 'LED pásik', types: ['5m teplá biela', '5m studená biela', '5m RGB', '5m RGBW', '12V', '24V', 'IP20', 'IP65'] },
    { name: 'Svietidlo', types: ['stropné', 'prisadené', 'nástenné', 'vonkajšie IP44', 'núdzové', 'do kúpeľne IP44'] },
    { name: 'Pohybový snímač PIR', types: ['stropný', 'nástenný', 'vstavaný', 'vonkajší IP65'] },
    { name: 'Snímač dymu', brands: ['Honeywell', 'Kidde', 'FireAngel'] },
    { name: 'Zvonček', brands: ['Legrand', 'Friedland'], types: ['drôtový', 'bezdrôtový', 'videovrátnik'] },
    { name: 'Stýkač', brands: ['OEZ', 'Eaton', 'ABB', 'Schneider'], types: ['20A 230V', '25A 230V', '40A 230V', '63A 230V', '1P', '2P', '4P'] },
    { name: 'Časový spínač', brands: ['Legrand', 'Hager', 'Schneider'], types: ['schodiskový automat', 'digitálny', 'analógový', 'týždenný'] },
    { name: 'Sťahovacia páska', types: ['100mm (100ks)', '200mm (100ks)', '300mm (100ks)', '400mm (100ks)', 'biela', 'čierna'] },
    { name: 'Uzemnenie', types: ['pásik FeZn 30x4 (m)', 'tyč 1,5m', 'svorka uzemňovacia', 'svorka ekvipotenciálna'] },
    // EV nabíjanie
    { name: 'Wallbox nabíjacia stanica EV', brands: ['ABB', 'Schneider', 'Keba', 'Mennekes', 'Webasto'], types: ['3,7kW 1P', '7,4kW 1P', '11kW 3P', '22kW 3P', 'Type 2', 'WiFi smart', 'so zmeračom'] },
    { name: 'Wallbox príslušenstvo', types: ['montážna konzola', 'Type 2 kábel 5m', 'Type 2 kábel 7m', 'ochranný kryt'] },
    // Meracie prístroje (materiál pre zákazníka)
    { name: 'Merač spotreby energie', brands: ['Schneider', 'Finder', 'Carlo Gavazzi'], types: ['jednofázový', 'trojfázový', 'DIN lišta', 'MID certifikovaný'] },
    // FVE príslušenstvo
    { name: 'FVE istič DC', brands: ['OEZ', 'ABB', 'Eaton'], types: ['10A', '16A', '20A', '32A', '1P DC', '2P DC'] },
    { name: 'FVE prúdový chránič typ B', brands: ['OEZ', 'ABB', 'Schneider'], types: ['25A/30mA 4P', '40A/30mA 4P', '63A/30mA 4P'] },
    { name: 'Kábel pre FVE DC', types: ['6mm² (m)', '10mm² (m)', '16mm² (m)', 'červený', 'čierny', 'UV odolný'] },
    { name: 'MC4 konektor', types: ['pár samec/samica', '10 párov'] },
    // Servisné meracie prístroje
    { name: 'Digitálny multimeter', brands: ['Fluke', 'UNI-T', 'Metrel'] },
    { name: 'Merač izolácie', brands: ['Metrel', 'Fluke', 'Kyoritsu'], types: ['500V', '1000V'] },
  ],

  // ─── 11. Electronics ──────────────────────────────────────────
  '11': [
    { name: 'Anténa', types: ['izbová DVB-T2', 'vonkajšia DVB-T2', 'satelitná'] },
    { name: 'Anténny zosilňovač', types: ['1 výstup', '2 výstupy', '4 výstupy'] },
    { name: 'Koaxiálny kábel', types: ['RG6 (m)', 'RG59 (m)'] },
    { name: 'F-konektor', types: ['štandardný', 'kompresný'] },
    { name: 'Ethernet kábel Cat6', types: ['1m', '2m', '3m', '5m', '10m', '20m', 'UTP', 'FTP'] },
    { name: 'Ethernet zásuvka', brands: ['ABB', 'Legrand', 'Schneider'], types: ['RJ45 Cat5e', 'RJ45 Cat6'] },
    { name: 'WiFi router', brands: ['TP-Link', 'Asus', 'Mikrotik', 'Ubiquiti'], types: ['WiFi 5', 'WiFi 6', 'WiFi 6E', 'mesh'] },
    { name: 'WiFi extender / AP', brands: ['TP-Link', 'Ubiquiti'], types: ['stropný', 'nástenný'] },
    { name: 'Switch', brands: ['TP-Link', 'Netgear', 'Mikrotik'], types: ['5-port', '8-port', '16-port', 'PoE'] },
    { name: 'UPS záložný zdroj', brands: ['APC', 'Eaton', 'CyberPower'], types: ['650VA', '750VA', '1000VA', '1500VA'] },
    { name: 'Smart termostat', brands: ['Tado', 'Netatmo', 'Honeywell', 'Google Nest'] },
    { name: 'Kamerový systém', brands: ['Hikvision', 'Dahua', 'Reolink'], types: ['IP kamera vnútorná', 'IP kamera vonkajšia', 'NVR 4ch', 'NVR 8ch', 'WiFi kamera'] },
  ],

  // ─── 12. Airconditioning ──────────────────────────────────────
  '12': [
    { name: 'Chladivo', types: ['R32 (1kg)', 'R410A (1kg)', 'R407C (1kg)', 'R134a (1kg)', 'R290 (1kg)'] },
    { name: 'Kompresorový olej', types: ['POE (0,5L)', 'PAG (0,5L)'] },
    { name: 'Filter klimatizácie', types: ['vnútorný štandard', 'vnútorný uhlíkový', 'vnútorný HEPA', 'sušiaci filter (okruh)'] },
    { name: 'Ventilátor vnútornej jednotky', brands: ['Daikin', 'Mitsubishi', 'Samsung', 'LG', 'Toshiba', 'Midea', 'Haier'] },
    { name: 'Ventilátor vonkajšej jednotky', brands: ['Daikin', 'Mitsubishi', 'Samsung', 'LG', 'Toshiba'] },
    { name: 'Motor ventilátora', types: ['vnútorný', 'vonkajší'] },
    { name: 'Riadiaca doska', brands: ['Daikin', 'Mitsubishi', 'Samsung', 'LG', 'Toshiba'], types: ['vnútorná', 'vonkajšia'] },
    { name: 'Diaľkový ovládač', brands: ['Daikin', 'Mitsubishi', 'Samsung', 'LG', 'Toshiba', 'univerzálny'] },
    { name: 'Snímač teploty', types: ['vnútorný', 'vonkajší', 'výparníka', 'kondenzátora'] },
    { name: 'Expanzný ventil', brands: ['Danfoss'] },
    { name: 'Štvorcestný ventil' },
    { name: 'Presostat', types: ['vysoký tlak', 'nízky tlak'] },
    { name: 'Rozbehovací kondenzátor', types: ['25µF', '30µF', '35µF', '40µF', '45µF', '50µF'] },
    { name: 'Drenážne čerpadlo', brands: ['Aspen', 'Sauermann'] },
    { name: 'Cu rúra', types: ['1/4" (m)', '3/8" (m)', '1/2" (m)', '5/8" (m)', '3/4" (m)'] },
    { name: 'Izolácia Cu rúry', types: ['1/4"', '3/8"', '1/2"', '5/8"'] },
    { name: 'Kondenzačná hadica', types: ['DN16', 'DN20', 'DN32'] },
    { name: 'Komunikačný kábel', types: ['2x1mm²', '3x1mm²', '4x1mm²'] },
    { name: 'Kanál dekoratívny', types: ['80x60', '110x75'] },
    { name: 'Držiak vonkajšej jednotky', types: ['nástenný', 'podlahový', 'strešný'] },
    { name: 'Antivibračné podložky' },
    { name: 'Priechodka stenová' },
    { name: 'Čistiaci prostriedok na klímu' },
    { name: 'Dezinfekcia klimatizácie' },
    // Tepelná izolácia
    { name: 'Tepelná izolácia Cu potrubia (Armaflex)', brands: ['Armacell Armaflex', 'K-Flex'], types: ['1/4" hr.10mm (m)', '3/8" hr.10mm (m)', '1/2" hr.10mm (m)', '5/8" hr.10mm (m)', '3/4" hr.13mm (m)', '1/4" hr.19mm (m)', '3/8" hr.19mm (m)'] },
    { name: 'Izolácia kondenzačnej hadice', types: ['DN16 (m)', 'DN20 (m)', 'DN32 (m)', 'čierna'] },
    // Náhradné diely split jednotky
    { name: 'Kompresor split jednotky', brands: ['Daikin', 'Mitsubishi', 'Samsung', 'LG', 'Toshiba', 'Panasonic', 'Copeland'] },
    { name: 'Rozbehovací kondenzátor split', types: ['25µF 450V', '30µF 450V', '35µF 450V', '40µF 450V', '45µF 450V', '50µF 450V'] },
    { name: 'Presostat split', types: ['vysoký tlak 4,1MPa', 'nízky tlak 0,4MPa', 'kombinovaný'] },
    { name: 'Drenážna vaňa split', types: ['vnútorná jednotka', 's čerpadlom'] },
    { name: 'WiFi modul klimatizácie', brands: ['Daikin', 'Mitsubishi', 'Samsung', 'LG', 'Toshiba', 'Intesis', 'Sensibo'] },
  ],

  // ─── 14. Keyservice ───────────────────────────────────────────
  '14': [
    { name: 'Cylindrická vložka', brands: ['FAB', 'FAB Assa Abloy', 'Mul-T-Lock', 'EVVA', 'DOM', 'Keso', 'Winkhaus'], types: ['30/30', '30/35', '35/35', '35/40', '40/40', '40/45', '40/50', '45/45', '45/50', '50/50', 's gombíkom', 'bezpečnostná BT3', 'bezpečnostná BT4'] },
    { name: 'Dverný zámok zadlabací', brands: ['FAB', 'AGB', 'Nemef'], types: ['72mm', '90mm', 'na kľúč', 'na cylindrickú vložku', 'viacbodový'] },
    { name: 'Zámok bezpečnostný', brands: ['FAB', 'Mul-T-Lock'], types: ['prídavný', 'viacbodový', 'dvojzámok'] },
    { name: 'Kľučka dverná', brands: ['Cobra', 'Dverkan', 'Hoppe', 'Rostex'], types: ['interiérová', 'exteriérová', 'bezpečnostná', 'na rozete', 'na štítku', 'nerez', 'chrómová', 'čierna'] },
    { name: 'Guľa dverná', brands: ['FAB', 'Cobra'], types: ['pevná', 'otočná'] },
    { name: 'Rozeta bezpečnostná', brands: ['FAB', 'Mul-T-Lock', 'Rostex'], types: ['okrúhla', 'štvorcová', 'nerez', 'chrómová'] },
    { name: 'Štítok dverný', types: ['kľučkový', 'guľový', 'slepý', 'bezpečnostný'] },
    { name: 'Protiplech', types: ['nastaviteľný', 'rohový', 'zaoblený', 'bezpečnostný'] },
    { name: 'Pánty dverné', types: ['2D', '3D nastaviteľné', '100mm', '120mm', '140mm'] },
    { name: 'Dverný zatvárač', brands: ['GEZE', 'Dorma', 'Assa Abloy'], types: ['horný', 'podlahový', 'skrytý', 'EN2', 'EN3', 'EN4', 'EN5'] },
    { name: 'Dverný reťazový poistka' },
    { name: 'Kukátko dverné', types: ['štandardné', 'digitálne', 'široký uhol'] },
    { name: 'Elektrický zámok', types: ['12V', '24V', 'samozatváracie', 'protipožiarne'] },
    { name: 'Kľúč duplikát', types: ['FAB štandard', 'bezpečnostný', 'systémový'] },
    // Trezory a špeciálne zámky
    { name: 'Trezorový zámok', brands: ['Fichet', 'Amsec', 'Mauer'], types: ['kľúčový', 'kombinačný', 'elektronický', 'súprava na výmenu'] },
    { name: 'Autoklúč transponder', types: ['kópia čipu T5', 'kópia čipu ID46', 'kópia čipu ID48', 'Smart kľúč programovanie'] },
    { name: 'FAB vložka bezpečnostná', brands: ['FAB Assa Abloy'], types: ['BT3 30/30', 'BT3 30/35', 'BT3 35/35', 'BT3 35/40', 'BT4 30/30', 'BT4 35/35', 'BT4 40/45', 'BT4 45/50'] },
    { name: 'Bezpečnostná fólia na dvere', types: ['transparentná', 'mliečna', 'proti vyrazeniu'] },
    { name: 'Dverný odpor (shock sensor)' },
    { name: 'Magnetický alarm na dvere/okno', types: ['drôtový', 'bezdrôtový', 'sada 2ks', 'sada 5ks'] },
  ],

  // ─── 15. Roof ─────────────────────────────────────────────────
  '15': [
    { name: 'Škridla', brands: ['Bramac', 'Tondach', 'Creaton', 'Wienerberger'], types: ['betónová', 'keramická', 'hrebenáčová', 'okrajová', 'vetracia'] },
    { name: 'Trapézový plech', types: ['T18 (m²)', 'T35 (m²)', 'T50 (m²)', 'pozinkovaný', 'lakovaný'] },
    { name: 'Šindeľ bitúmenový', brands: ['IKO', 'Tegola', 'GAF'], types: ['3-tab (m²)', 'architektonický (m²)'] },
    { name: 'Strešná fólia', brands: ['Tyvek', 'Jutadach', 'Delta'], types: ['paropriepustná (m²)', 'parozábrana (m²)', 'difúzna'] },
    { name: 'Strešná lata', types: ['30x50mm (m)', '40x60mm (m)', '50x50mm (m)'] },
    { name: 'Kontralata', types: ['40x60mm (m)', '60x60mm (m)'] },
    { name: 'Izolácia strešná', brands: ['Isover', 'Knauf Insulation', 'Rockwool'], types: ['100mm (m²)', '150mm (m²)', '200mm (m²)', '250mm (m²)', 'medzi krokvy', 'pod krokvy'] },
    { name: 'Odkvapový žľab', types: ['100mm (m)', '125mm (m)', '150mm (m)', 'plastový', 'plechový', 'medený'] },
    { name: 'Žľabový hák', types: ['100mm', '125mm', '150mm', 'krátky', 'dlhý'] },
    { name: 'Žľabový roh', types: ['vnútorný', 'vonkajší', '90°'] },
    { name: 'Žľabový kotlík', types: ['100mm', '125mm', '150mm'] },
    { name: 'Zvod dažďový', types: ['75mm (m)', '87mm (m)', '100mm (m)', '120mm (m)'] },
    { name: 'Zvodové koleno', types: ['75mm', '87mm', '100mm', '120mm'] },
    { name: 'Oplechovanie', types: ['komína', 'múru', 'odkvapovej hrany', 'štítu'] },
    { name: 'Strešné okno', brands: ['Velux', 'Fakro', 'Roto'], types: ['55x78', '66x118', '78x98', '78x118', '78x140', '114x118', 'kyvné', 'výklopno-kyvné'] },
    { name: 'Snehová zábrana', types: ['bodová', 'mriežková', 'rúrková'] },
    { name: 'Strešný kit / tmel' },
    { name: 'Bitúmenový pás', types: ['podkladový', 'vrchný', 'samolepiaci'] },
    // Bezpečnosť a prístup na strechu
    { name: 'Strešný výlez', brands: ['Velux', 'Fakro', 'Dolle'], types: ['550x700mm', '600x800mm', '700x900mm', '800x1000mm', 'drevený', 'PVC', 'hliníkový', 'zateplený'] },
    { name: 'Odvetrávacia hlavica', brands: ['Nicoll', 'Wirplast', 'Lomanco'], types: ['DN75', 'DN110', 'DN125', 'DN160', 'plastová', 'nerezová', 'so spätnou klapkou'] },
    { name: 'Strešná lávka', brands: ['Bramac', 'Tondach', 'Meindl'], types: ['1,2m oceľová', '1,5m oceľová', '2m oceľová', 'hliníková', 's hákmi'] },
    { name: 'Bezpečnostný strešný hák', types: ['pevný', 'sklopný', 'pre lano', 'nerez', 'pozinkovaný'] },
    { name: 'Strešný vetrák', brands: ['Lomanco', 'Nicoll', 'Air-Con'], types: ['universálny pre škridlu', 'pre trapézový plech', 'aktívny', 'pasívny'] },
    { name: 'Hrebňová vetracia páska', brands: ['Bramac', 'Tondach', 'Delta'], types: ['5m', '10m', '50mm', '100mm'] },
    { name: 'Muflón strešný (manžeta pre potrubie)', brands: ['Wirplast', 'Wakaflex'], types: ['DN75', 'DN110', 'DN125', 'DN160', 'DN200', 'pre šikmú strechu', 'pre rovnú strechu'] },
  ],

  // ─── 16. Tiles ────────────────────────────────────────────────
  '16': [
    { name: 'Lepidlo na obklady', brands: ['Mapei', 'Ceresit', 'Weber', 'Baumit', 'Sika'], types: ['štandardné (25kg)', 'flexibilné (25kg)', 'rýchloschnúce (25kg)', 'na veľkoformáty (25kg)', 'na bazény (25kg)', 'C1', 'C2', 'C2TE'] },
    { name: 'Škárovacia hmota', brands: ['Mapei', 'Ceresit', 'Weber', 'Baumit'], types: ['2kg', '5kg', 'cementová', 'epoxidová', 'rôzne farby'] },
    { name: 'Silikón sanitárny', brands: ['Soudal', 'Den Braven', 'Mapei', 'Ceresit'], types: ['biely', 'transparentný', 'sivý', 'béžový', 'hnedý', 'čierny'] },
    { name: 'Penetrácia', brands: ['Ceresit', 'Weber', 'Baumit'], types: ['hĺbková (5L)', 'hĺbková (10L)', 'kontaktná (5L)'] },
    { name: 'Hydroizolácia tekutá', brands: ['Mapei', 'Ceresit', 'Weber', 'Sika'], types: ['1-zložková (5kg)', '1-zložková (15kg)', '2-zložková'] },
    { name: 'Hydroizolačná páska', types: ['120mm', 'rohová vnútorná', 'rohová vonkajšia', 'manžeta na rúru'] },
    { name: 'Nivelačná stierka', brands: ['Ceresit', 'Weber', 'Baumit'], types: ['25kg'] },
    { name: 'Rohová lišta', types: ['vnútorná 8mm', 'vonkajšia 8mm', 'vnútorná 10mm', 'vonkajšia 10mm', 'vnútorná 12mm', 'vonkajšia 12mm', 'PVC', 'hliníková', 'nerez'] },
    { name: 'Prechodová lišta', types: ['plochá', 'T-profil', 'výšková', 'hliníková', 'nerez'] },
    { name: 'Dilatačný profil' },
    { name: 'Nivelačné kríže', types: ['1mm (100ks)', '1,5mm (100ks)', '2mm (100ks)', '3mm (100ks)', '5mm (100ks)'] },
    { name: 'Nivelačný systém', types: ['klipy (100ks)', 'kliny (100ks)', 'kliešte'] },
    { name: 'Rezný kotúč diamantový', types: ['115mm', '125mm', '180mm', '230mm', 'na dlažbu', 'na obklad', 'na porcelán'] },
    { name: 'Dierovka diamantová', types: ['6mm', '8mm', '10mm', '12mm', '14mm', '20mm', '25mm', '32mm', '35mm', '45mm', '65mm', '83mm', '110mm'] },
    // Špeciálne dlažby a obklady
    { name: 'Dlažba protišmyková', types: ['R10 (m²)', 'R11 (m²)', 'R12 (m²)', '30x30cm', '40x40cm', '60x60cm', 'terasa', 'kúpeľňa', 'šedá', 'béžová'] },
    { name: 'Veľkoformátová dlažba', types: ['60x60cm (m²)', '60x120cm (m²)', '80x80cm (m²)', '100x100cm (m²)', 'rektifikovaná', 'matná', 'lesklá'] },
    { name: 'Mozaika', types: ['30x30cm sieť', 'sklenená', 'kamenná', 'porcelánová', 'biela', 'sivá', 'mix farieb'] },
    { name: 'Kamenný obklad', types: ['bridlica (m²)', 'pieskoviec (m²)', 'travertín (m²)', 'hrúbka 1-2cm', 'hrúbka 2-3cm', 'dekoratívny panel'] },
    { name: 'Obklad dekoratívny 3D', types: ['biely', 'sivý', '50x50cm', '30x60cm', 'sadrokartónový', 'polyuretánový'] },
    { name: 'Flexibilné lepidlo na veľkoformáty', brands: ['Mapei Ultralite', 'Ceresit CM17', 'Weber.col flex'], types: ['C2TE 25kg', 'C2ES1 25kg', 'biely', 'šedý'] },
  ],

  // ─── 17. Flooring ─────────────────────────────────────────────
  '17': [
    { name: 'Laminátová podlaha', brands: ['Quick-Step', 'Egger', 'Classen', 'Kronospan', 'Parador'], types: ['AC3 (m²)', 'AC4 (m²)', 'AC5 (m²)', '7mm', '8mm', '10mm', '12mm', 'dub', 'buk', 'orech', 'sivá'] },
    { name: 'Vinylová podlaha', brands: ['Quick-Step', 'Wineo', 'Gerflor', 'Tarkett'], types: ['click (m²)', 'lepená (m²)', '4mm', '5mm', '6mm', 'SPC', 'WPC', 'dub', 'betón', 'kameň'] },
    { name: 'PVC krytina', brands: ['Tarkett', 'Gerflor', 'IVC'], types: ['m²', '2m šírka', '3m šírka', '4m šírka'] },
    { name: 'Drevená podlaha', brands: ['Barlinek', 'Kährs', 'Quick-Step'], types: ['masív (m²)', 'vrstvená (m²)', 'dub', 'jaseň', 'orech', '14mm', '20mm'] },
    { name: 'Podložka pod podlahu', brands: ['Mirelon', 'Selit', 'Quick-Step'], types: ['PE 2mm (m²)', 'PE 3mm (m²)', 'XPS 3mm (m²)', 'XPS 5mm (m²)', 'kork 2mm (m²)', 's parozábranou (m²)'] },
    { name: 'Soklová lišta', types: ['PVC 2,5m', 'MDF 2,4m', 'hliníková', 'biela', 'dub', 'k podlahe'] },
    { name: 'Prechodový profil', types: ['plochý', 'T-profil', 'výškový', 'schodový', 'hliníkový', 'samolepiacii', 'vŕtaný'] },
    { name: 'Nivelačná stierka', brands: ['Ceresit', 'Weber', 'Baumit'], types: ['25kg'] },
    { name: 'Lepidlo na podlahu', types: ['na PVC (1kg)', 'na koberec (1kg)', 'na vinyl (1kg)', 'na parkety (1kg)', 'fixačné'] },
  ],

  // ─── 18. Painting ─────────────────────────────────────────────
  '18': [
    { name: 'Interiérová farba', brands: ['Primalex', 'Dulux', 'Jupol', 'Caparol', 'HET', 'Remal'], types: ['biela 5L', 'biela 10L', 'biela 15L', 'biela 25L', 'umývateľná 5L', 'umývateľná 10L', 'farebná 2,5L', 'farebná 5L', 'do kúpeľne', 'do kuchyne', 'latex', 'matná', 'polomatná'] },
    { name: 'Fasádna farba', brands: ['Caparol', 'Baumit', 'Weber', 'Ceresit', 'JUB'], types: ['5L', '10L', '15L', '25L', 'akrylová', 'silikónová', 'silikátová'] },
    { name: 'Email/lak', types: ['syntetický biely 0,75L', 'syntetický biely 2,5L', 'vodou riediteľný 0,75L', 'na radiátory 0,75L', 'na kov 0,75L', 'na drevo 0,75L', 'na podlahu 2,5L', 'bezfarebný 0,75L', 'antikorózny 0,75L', 'matný', 'lesklý', 'polomatný'] },
    { name: 'Penetračný náter', brands: ['Primalex', 'Ceresit', 'Baumit', 'HET'], types: ['5L', '10L', 'hĺbkový', 'kontaktný'] },
    { name: 'Tmel vyrovnávací', types: ['5kg', '15kg', '25kg', 'sádrový', 'cementový'] },
    { name: 'Tmel akrylový', brands: ['Soudal', 'Den Braven'], types: ['biely 310ml', 'biely 600ml', 'šedý', 'hnedý'] },
    { name: 'Sádrový tmel na SDK', brands: ['Knauf', 'Rigips'], types: ['5kg', '25kg', 'Uniflott', 'Fugenfuller'] },
    { name: 'Výstužná páska', types: ['papierová', 'sklenená samolepiaca', 'na SDK', 'na praskliny'] },
    { name: 'Brúsny papier', types: ['P60', 'P80', 'P100', 'P120', 'P150', 'P180', 'P220', 'sada', 'háčiky (pre brúsku)'] },
    { name: 'Brúsna mriežka na SDK', types: ['P100', 'P120', 'P150', 'P180'] },
    { name: 'Maliarsky valec', types: ['10cm', '18cm', '25cm', 'pena (lak)', 'mikrovlákno', 'polyamid', 'fasádny'] },
    { name: 'Štetec plochý', types: ['20mm', '30mm', '40mm', '50mm', '60mm', '70mm', '100mm'] },
    { name: 'Maliarska páska', types: ['30mm', '38mm', '48mm', 'pre ostré hrany', 'pre oblúky'] },
    { name: 'Zakrývacia fólia', types: ['4x5m', '4x12,5m', 's páskou'] },
    { name: 'Stierka nerezová', types: ['250mm', '300mm', '400mm', '500mm', '600mm', '800mm'] },
    { name: 'Špachtľa', types: ['40mm', '60mm', '80mm', '100mm', '120mm', '150mm'] },
    { name: 'Tapeta', types: ['vliesová (rolka)', 'vinylová (rolka)', 'papierová (rolka)'] },
    { name: 'Lepidlo na tapety', types: ['250g', '500g', 'vliesové', 'univerzálne'] },
  ],

  // ─── 19. Masonry ──────────────────────────────────────────────
  '19': [
    { name: 'Tvárnica', brands: ['Ytong', 'Porotherm', 'Liapor'], types: ['100mm', '150mm', '200mm', '250mm', '300mm', '375mm', 'presná P2-400', 'presná P2-500'] },
    { name: 'Malta', brands: ['Ytong', 'Baumit', 'Weber'], types: ['lepidlo na Ytong (25kg)', 'murárska (25kg)', 'cementová (25kg)', 'vápenno-cementová (25kg)'] },
    { name: 'Cement', types: ['portlandský 25kg', 'rýchlotuhnúci 25kg'] },
    { name: 'Betón', types: ['rýchly 25kg', 'suchá zmes 25kg'] },
    { name: 'SDK doska', brands: ['Knauf', 'Rigips', 'Siniat'], types: ['štandard 12,5mm (biela)', 'impregnovaná 12,5mm (zelená)', 'protipožiarna 12,5mm (ružová)', 'protipožiarna 15mm', 'akustická 12,5mm', 'cementová 12mm'] },
    { name: 'SDK profil', types: ['CD 60 3m', 'CD 60 4m', 'UD 28 3m', 'UD 28 4m', 'CW 50 3m', 'CW 50 4m', 'CW 75 3m', 'CW 75 4m', 'CW 100 3m', 'CW 100 4m', 'UW 50 3m', 'UW 50 4m', 'UW 75 3m', 'UW 75 4m', 'UW 100 3m', 'UW 100 4m', 'UA 50 3m', 'UA 75 3m'] },
    { name: 'Záves rýchlý (Nonius)', types: ['horný', 'dolný', 'kombinovaný'] },
    { name: 'Spojka CD profilov', types: ['predĺžovacia', 'krížová'] },
    { name: 'Skrutka SDK', types: ['3,5x25mm (1000ks)', '3,5x35mm (1000ks)', '3,5x45mm (500ks)', '3,5x55mm (500ks)', '3,9x13mm do kovu (1000ks)'] },
    { name: 'Sádrová stierka', brands: ['Knauf', 'Rigips'], types: ['5kg', '25kg', 'Uniflott', 'Fugenfuller', 'finálna'] },
    { name: 'Omietka', brands: ['Baumit', 'Weber', 'Ceresit', 'Knauf'], types: ['vnútorná sádrová (25kg)', 'vnútorná vápenná (25kg)', 'vnútorná cementová (25kg)', 'vonkajšia silikónová', 'vonkajšia silikátová', 'štuková'] },
    { name: 'Armovacia sieťka', types: ['160g/m² (m²)', 'perlinka', 'rohová lišta s perlinkou'] },
    { name: 'Izolácia', brands: ['Isover', 'Knauf Insulation', 'Rockwool'], types: ['minerálna vlna 50mm (m²)', 'minerálna vlna 100mm (m²)', 'minerálna vlna 150mm (m²)', 'minerálna vlna 200mm (m²)', 'EPS 50mm (m²)', 'EPS 80mm (m²)', 'EPS 100mm (m²)', 'EPS 150mm (m²)', 'XPS 50mm (m²)', 'XPS 80mm (m²)'] },
    { name: 'Hmoždinka', types: ['univerzálna 6x40 (sada)', 'univerzálna 8x50 (sada)', 'univerzálna 10x60 (sada)', 'do SDK kovová (Molly)', 'do SDK plastová', 'do SDK sklopná', 'talierová pre EPS 8x60', 'talierová pre EPS 8x100'] },
    { name: 'Kotviaca skrutka do betónu', types: ['6x40', '6x60', '8x60', '8x80', '10x80', '10x100'] },
    { name: 'Chemická kotva', brands: ['Fischer', 'Hilti', 'Soudal'], types: ['300ml', '380ml', '585ml'] },
    { name: 'Montážna pena PU', brands: ['Soudal', 'Den Braven', 'Fischer'], types: ['750ml štandard', '750ml nízkoexpanzná', '750ml protipožiarna', 'pištolová'] },
    { name: 'Preklad', brands: ['Ytong', 'Porotherm'], types: ['100cm', '125cm', '150cm', '175cm', '200cm', '250cm'] },
    { name: 'OSB doska', types: ['12mm (m²)', '15mm', '18mm (m²)', '22mm (m²)'] },
    // Betónové hmoty
    { name: 'Pohľadový betón (štukatúra)', brands: ['Baumit', 'Caparol', 'Betoniu'], types: ['5kg', '15kg', 'interiérový', 'exteriérový', 'svetlošedý', 'tmavošedý', 'biely'] },
    { name: 'Betónová zálievka', brands: ['Sika', 'Mapei', 'Baumit'], types: ['25kg', 'rýchlotuhnúca', 'bez zmrašťovania', 'SikaGrout'] },
    { name: 'Samonivelačná stierka rýchla', brands: ['Ceresit', 'Weber', 'Baumit', 'Knauf'], types: ['25kg do 30mm', '25kg do 60mm', '25kg do 80mm', 'výstužová', 'záverová'] },
    { name: 'Kontaktná stierka ETICS', brands: ['Baumit', 'Weber', 'Caparol'], types: ['25kg', 'šedá', 'biela', 'so sieťkou'] },
    { name: 'Vyrovnávacia malta', brands: ['Baumit', 'Weber', 'Mapei'], types: ['25kg', 'do 30mm', 'cementová', 'rýchloviažuca'] },
  ],

  // ─── 20. Deratization ─────────────────────────────────────────
  '20': [
    { name: 'Rodenticíd', types: ['granulát (1kg)', 'pasta (1kg)', 'blok voskový', 'tekutý'] },
    { name: 'Deratizačná stanica', types: ['plastová', 'kovová', 'na myši', 'na potkany'] },
    { name: 'Pasca', types: ['na myši mechanická', 'na myši lepová', 'na potkany mechanická', 'na potkany živolovná'] },
    { name: 'Insekticíd', types: ['spray (400ml)', 'prášok (1kg)', 'gél na šváby', 'fumigátor', 'koncentrát (1L)'] },
    { name: 'Repelent ultrazvukový' },
    { name: 'Dezinfekčný prostriedok', types: ['1L', '5L'] },
    { name: 'Ochranné pomôcky', types: ['rukavice', 'respirátor', 'okuliare', 'ochranný oblek'] },
    { name: 'Tesniaci materiál na diery' },
    { name: 'Sieťka proti hmyzu', types: ['na okno', 'na dvere', 'roleta'] },
    { name: 'Mriežka vetracia s filtrom', types: ['150x150mm', '200x200mm', '300x300mm'] },
  ],

  // ─── 21. Water systems ────────────────────────────────────────
  '21': [
    { name: 'Domáca vodáreň', brands: ['Grundfos', 'DAB', 'Wilo'], types: ['s tlakovou nádobou', 'frekvenčne riadená'] },
    { name: 'Ponorné čerpadlo', brands: ['Grundfos', 'DAB', 'Wilo'], types: ['3"', '4"', 'do 30m', 'do 50m', 'do 80m', 'do 100m'] },
    { name: 'Kalové čerpadlo', brands: ['Grundfos', 'DAB', 'Wilo'], types: ['pre čistú vodu', 'pre špinavú vodu', 'ponorné'] },
    { name: 'Tlaková nádoba', brands: ['Flamco', 'Varem', 'Zilmet', 'Reflex'], types: ['8L', '24L', '50L', '80L', '100L', '200L'] },
    { name: 'Tlakový spínač', types: ['1-5 bar', '2-6 bar', 'nastaviteľný'] },
    { name: 'Filter na studňu', types: ['mechanický', 'piesočnatý', 'uhlíkový', 'železitý', 'dusičnanový'] },
    { name: 'UV sterilizátor vody', types: ['do 1m³/h', 'do 2m³/h'] },
    { name: 'Zmäkčovač vody', brands: ['BWT', 'Ecosoft', 'Watex'], types: ['kabinet', 'dvojstĺpový'] },
    { name: 'Soľ do zmäkčovača', types: ['25kg tabletová'] },
    { name: 'HDPE rúra', types: ['25mm (m)', '32mm (m)', '40mm (m)', '50mm (m)', '63mm (m)', 'PN10', 'PN16'] },
    { name: 'HDPE spojka', types: ['25mm', '32mm', '40mm', '50mm', '63mm', 'priama', 'prechodová'] },
    { name: 'HDPE koleno', types: ['25mm', '32mm', '40mm', '90°', '45°'] },
    { name: 'HDPE T-kus', types: ['25mm', '32mm', '40mm'] },
    { name: 'Navrtávací pás', types: ['DN50', 'DN63', 'DN90', 'DN110'] },
    { name: 'Šupátkový ventil', types: ['1"', '5/4"', '6/4"', '2"'] },
    { name: 'Vodomerná šachta', types: ['plastová', 'betónová'] },
    // Studňové príslušenstvo
    { name: 'Studňové lano a príslušenstvo', types: ['nerezové lano 5mm (m)', 'klips na lano', 'nosná vidlica', 'závesná sada pre čerpadlo'] },
    { name: 'Hadica tlaková čerpacie', brands: ['Gardena', 'Alfaflex'], types: ['3/4" 10m', '3/4" 20m', '1" 10m', '1" 20m', 'PN10', 'PN16', 'spätný ventil + koncovky'] },
    { name: 'Zpevňovacia sieť studne', types: ['nerezová pletivo DN800', 'nerezová pletivo DN1000', 'plastová'] },
    // Potrubie HDPE (rozšírenie)
    { name: 'HDPE potrubie tlakovania', types: ['63mm PN10 (m)', '90mm PN10 (m)', '110mm PN10 (m)', '125mm PN10 (m)', '160mm PN10 (m)'] },
    { name: 'HDPE redukcia', types: ['63/50mm', '63/40mm', '90/63mm', '110/90mm', '110/63mm'] },
    { name: 'HDPE elektrotvarovka', brands: ['Georg Fischer', 'Plasson'], types: ['spojka 32mm', 'spojka 40mm', 'spojka 50mm', 'spojka 63mm', 'koleno 90° 32mm', 'koleno 90° 50mm'] },
    { name: 'Priechodka základom pre potrubie', types: ['DN40', 'DN50', 'DN63', 'DN110', 'tesniaca', 'nerezová'] },
  ],
}

// ═══════════════════════════════════════════════════════════════════
// UNIVERSAL MATERIALS (shown for every category)
// ═══════════════════════════════════════════════════════════════════

const UNIVERSAL_MATERIALS: MaterialItem[] = [
  { name: 'Silikón', brands: ['Soudal', 'Den Braven', 'Mapei', 'Ceresit'], types: ['sanitárny biely', 'sanitárny transparentný', 'univerzálny', 'neutrálny', 'protipožiarny'] },
  { name: 'Montážna pena', brands: ['Soudal', 'Den Braven', 'Fischer'], types: ['750ml štandard', '750ml nízkoexpanzná', '750ml protipožiarna', 'pištolová'] },
  { name: 'Akrylový tmel', brands: ['Soudal', 'Den Braven'], types: ['biely 310ml', 'biely 600ml', 'šedý'] },
  { name: 'Montážne lepidlo', brands: ['Soudal', 'Pattex'], types: ['310ml', '400ml'] },
  { name: 'Teflónová páska', types: ['12mm', '19mm'] },
  { name: 'Tesniaca pasta + konope' },
  { name: 'Izolačná páska', types: ['čierna', 'biela', 'červená', 'žltá/zelená', 'sada'] },
  { name: 'Lepiaca páska strieborná (duct tape)' },
  { name: 'Skrutky', types: ['sada rôzne', 'do SDK', 'do dreva', 'do kovu', 'samorezy'] },
  { name: 'Hmoždinky', types: ['univerzálne 6mm (sada)', 'univerzálne 8mm (sada)', 'do SDK', 'do betónu'] },
  { name: 'Sťahovacia páska', types: ['100mm', '200mm', '300mm', 'biela', 'čierna'] },
  { name: 'WD-40', brands: ['WD-40'], types: ['200ml', '400ml'] },
  { name: 'Kontaktný sprej' },
  { name: 'Odmasťovač' },
  { name: 'Ochranné rukavice', types: ['latex', 'nitrilové', 'pracovné'] },
  { name: 'Zakrývacia fólia', types: ['4x5m', '4x12,5m'] },
]
